### ISSUE TITLE
WARNING: 10 documents displayed are out-of-date. Please run the following command: 'ivre view --update-schema;

### ISSUE THREAD

**Issue by ubushan** [cea-sec/ivre#1003]
### IVRE Version
```
IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.15

Python 2.7.17 (default, Sep 30 2020, 13:38:04)
[GCC 7.5.0]

Linux Bender 5.4.0-1026-azure #26~18.04.1-Ubuntu SMP Thu Sep 10 16:19:25 UTC 2020 x86_64

Dependencies:
    Python module pymongo: 3.10.1
    Python module py2neo: missing
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module cryptography: 2.2.2
    Python module krbV: missing
    Python module PIL: missing
    Python module MySQLdb: missing
    Python module dbus: 1.2.6
    Python module matplotlib: missing
    Python module bottle: 0.12.18
    Python module OpenSSL: 19.1.0
    Python module tinydb: missing
```

Please tell me why am I always getting this notification in web interface `WARNING: 10 documents displayed are out-of-date. Please run the following command: 'ivre view --update-schema` and after running this command ʻivre view --update-schema` this notification does not disappear.
And also please tell me how to update IVRE without uninstalling and installing.

Thanks.

**Comment by p-l-** [comment]
How to install / update IVRE highly depends on how you installed it in the first place. If you used `pip`, you can probably use `pip install -U`.

I **think** your main issue here is that the client you use to import results is **not** the same version as the one used by your web server.

One thing you could do to make sure is to get your mouse over "IVRE" the top-left corner of the Web interface, as shown in the picture below.

![ivre-web-version](https://user-images.githubusercontent.com/5064814/96499754-20aeae80-124e-11eb-8239-12a1c5b554cb.png)

Both versions (from `ivre version` and from the Web interface) should match. If they don't, then you have probably installed IVRE twice (for example, one used by your regular user, and one used by your web server).

Another check you could to is to run, exactly where you have inserted the results, something like `ivre httpd -p 8080` and point your browser to `http://127.0.0.1:8080`.

**Comment by ubushan** [comment]
Yes, that's exactly how I have it, different versions in the web interface and in the сli.
Tell me please, how to reinstall IVRE correctly?

Thanks.

**Comment by p-l-** [comment]
I don't know how you installed it in the first place! You have to remove the different IVRE versions from your system (not you data, not your database, only IVRE installations). To know where IVRE is installed you can run:
```
$ which ivre
$ python -c "import ivre; print(ivre.__file__)"
```

This will tell you where the IVRE you are using from the command line is installed. Then you can try running the same command as the user that runs the web server (depending on your set-up, it might be `www-data` for example). If you have sudo on your system, you can run (as `root` or as another user that can sudo to your `www-data` user): 
```
$ sudo -H -u www-data which ivre
$ sudo -H -u nobody python -c "import ivre; print(ivre.__file__)"
```

Then, the important part is to install IVRE only once, probably using either a distribution package (or pip, probably as root in that case).

**Comment by ubushan** [comment]
That fixed my problem. @p-l- thanks a lot for a your quick response!
