### ISSUE TITLE
Structured output for ntlm-info scripts should be the same from zgrab2 and nmap

### ISSUE THREAD

**Issue by p-l-** [cea-sec/ivre#1011]
The keys when importing a Zgrab2 results are (**structured output**):
```
domain
domain-dns
name
name-dns
ntlm-os
ntlm-version
target
tree-dns
```
And from Nmap:
```
DNS_Computer_Name
DNS_Domain_Name
DNS_Tree_Name
NetBIOS_Computer_Name
NetBIOS_Domain_Name
Product_Version
Target_Name
```

The ones from Zgrab2 are better (IMO) but the ones from Nmap are a "de facto standard", so I **think** we should use them.

What do you think @Rhaev3n?

**Comment by Rhaev3n** [comment]
I agree with you that we should use the same keys for all the different ways we use to import NTLM information, and that the ones from Nmap are the best to keep. 

Therefore not only the keys of Zgrab2 results (assigned in the analyzer/ntlm module) but also the keys used when importing passive results from the zeek module (which are the same as the Zgrab2 ones) should be changed to match the Nmap keys.
