### ISSUE TITLE
`ivre scan2db` crashes (error with hostnames?)

### ISSUE THREAD

**Issue by sonnetmia** [cea-sec/ivre#1017]
### IVRE Version 
```
IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.15.dev186

Python 3.8.6 (default, Sep 25 2020, 09:36:53) 
[GCC 10.2.0]

Linux kali-ivre-s-2vcpu-4gb-sfo3-01 5.8.0-kali3-amd64 #1 SMP Debian 5.8.14-1kali1 (2020-10-13) x86_64

Dependencies:
    Python module pymongo: 3.11.0
    Python module sqlalchemy: 1.3.19
    Python module psycopg2: 2.8.5 (dt dec pq3 ext lo64)
    Python module cryptography: 3.1
    Python module krbV: missing
    Python module PIL: 8.0.1
    Python module MySQLdb: 1.4.4
    Python module dbus: 1.2.16
    Python module matplotlib: 3.3.2
    Python module bottle: 0.12.15
    Python module OpenSSL: 19.1.0
    Python module tinydb: 3.15.2

usage: ivre [COMMAND]
available commands:
  airodump2db
  arp2db
  auditdom
  db2view
  flow2db
  flowcli
  getmoduli
  httpd
  ipcalc
  ipdata
  iphost
  ipinfo
  macinfo
  passiverecon2db
  passivereconworker
  plotdb
  runscans
  runscansagent
  runscansagentdb
  scan2db
  scancli
  scanstatus
  version
  view
  zeek2db

Try ivre help [COMMAND]

```

### Summary

I am just experimenting these are tools. Followed all guidelines from your documentation. while I am trying to scan2db for my fist scan I am getting this error. 

```
ivre runscans --network 89.211.8.0/21 --output=XMLFork
ivre scan2db -c NET-89.211.8.0-21 -s NET-89.211.8.0-21 -r /root/scans/NET-89.211.8.0-21/up
```

### Expected behavior
I should able to view this into my web GUI. 

### Actual behavior
But this commands returns with error. 

Command is: 
```
ivre scan2db -c NET-89.211.8.0-21 -s NET-89.211.8.0-21 -r /root/scans/NET-89.211.8.0-21/up
```
Output Result: 

```
WARNING:ivre:Exception (file '/root/scans/NET-89.211.8.0-21/up/89/211/13/175.xml')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ivre/tools/scan2db.py", line 117, in main
    if database.store_scan(
  File "/usr/local/lib/python3.8/dist-packages/ivre/db/__init__.py", line 1786, in store_scan
    return store_scan_function(fname, filehash=scanid, **kargs)
  File "/usr/local/lib/python3.8/dist-packages/ivre/db/__init__.py", line 1814, in store_scan_xml
    parser.parse(utils.open_file(fname))
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.8/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "../Modules/pyexpat.c", line 459, in EndElement
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 336, in end_element
    self._cont_handler.endElement(name)
  File "/usr/local/lib/python3.8/dist-packages/ivre/xmlnmap.py", line 2070, in endElement
    self._curhost['hostnames'] = self._curhostnames
TypeError: 'NoneType' object does not support item assignment
INFO:ivre:0 results imported.

```

Finally, I am stuck here. Need the best suggestion to resolve the issue. 

Thank you.

**Comment by p-l-** [comment]
Hi,

Thanks for reporting this issue. This has nothing to do with python-krbV so I am changing the title.

It looks like a bug in the IVRE's Nmap XML parser. Could you share the file `/root/scans/NET-89.211.8.0-21/up/89/211/13/175.xml`?

Thanks!

**Comment by sonnetmia** [comment]
[175.xml.zip](https://github.com/cea-sec/ivre/files/5492585/175.xml.zip)

Here is the file. 
Thank you.

**Comment by p-l-** [comment]
The patch in #1019 should fix your issue. Can you apply it and report here if it works for you?

**Comment by sgros** [comment]
I also stumbled on this bug. I'm using version 0.9.15 which was released after this patch was applied, so any reason why it is not in the release?

**Comment by p-l-** [comment]
Hi @sgros!

It would probably help if you could share a sample that triggers this bug.

**Comment by sgros** [comment]
It's the same bug as the original poster reported, cause by the same XML structure. The bug is fixed in the master, but in the release 0.9.15 there's no fix (xmlnmap.py is the same as before the patch).

The problem is that Kali ships releases, and the latest is 0.9.15 which makes this bug still present.

**Comment by p-l-** [comment]
So you can confirm that, if you apply the fix, from #1019 it works fine for you?

If so, a new release should happen within the next week, so it should be fixed soon.

**Comment by sgros** [comment]
We applied a fix, and I can confirm that the bug is gone.

**Comment by p-l-** [comment]
You can track the Kali package update [here](https://gitlab.com/kalilinux/packages/ivre/-/issues/2)
