### ISSUE TITLE
"ivre db2view nmap" crashes with "AttributeError: 'list' object has no attribute 'union'" after update

### ISSUE THREAD

**Issue by duncrow** [cea-sec/ivre#1020]
### IVRE Version

IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.15.dev70

Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0]

Linux IVRE 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64

Dependencies:
    Python module pymongo: 3.7.1
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module cryptography: 2.6.1
    Python module krbV: missing
    Python module PIL: missing
    Python module MySQLdb: missing
    Python module dbus: 1.2.8
    Python module matplotlib: missing
    Python module bottle: missing
    Python module OpenSSL: 19.0.0
    Python module tinydb: missing

### Summary

Updated to the latest github sources today, did a "python3 setup.py build", "python3 setup.py install" and a "ivre view --update-schema" afterwards.

Running "ivre db2view nmap" produces the following error:

WARNING:ivre:Will not handle record with schema_version 16 (18 needed) [{'_id': ObjectId('5e9f3926b17b1e2ca0c5b480'), 'scanid': '870d92996eb0ec26413d513661d2cbc3ad7dbf712b5b0a520f82a8dfacba855e', 'state_reason_ttl': 50, 'state_reason': 'reset', 'schema_version': 16, 'state': 'up', 'hostnames': [{'domains': ['scanme.nmap.org', 'nmap.org', 'org'], 'type': 'user', 'name': 'scanme.nmap.org'}, {'domains': ['scanme.nmap.org', 'nmap.org', 'org'], 'type': 'PTR', 'name': 'scanme.nmap.org'}], 'starttime': datetime.datetime(2020, 4, 21, 18, 19, 16), 'openports': {'count': 1, 'tcp': {'count': 1, 'ports': [80]}}, 'infos': {'city': 'Fremont', 'region_code': ['CA'], 'region_name': ['California'], 'continent_code': 'NA', 'coordinates_accuracy_radius': 1000,
'country_name': 'United States', 'registered_country_code': 'US', 'registered_country_name': 'United States', 'country_code': 'US', 'continent_name': 'North America', 'postal_code': '94536', 'as_name': 'Linode, LLC', 'as_num': 63949, 'coordinates': [37.5625, -122.0004]}, 'endtime': datetime.datetime(2020, 4, 21, 18, 19, 17), 'ports': [{'state_state': 'open', 'state_reason_ttl': 50, 'protocol': 'tcp', 'port': 80, 'state_reason': 'syn-ack'}, {'state_state': 'closed', 'state_reason_ttl': 50, 'protocol': 'tcp', 'port': 443, 'state_reason': 'reset'}], 'addr': '45.33.32.156'}]
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 95, in <module>
    main()
  File "/usr/local/bin/ivre", line 66, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.7/dist-packages/ivre/tools/db2view.py", line 103, in main
    for elt in itr:
  File "/usr/local/lib/python3.7/dist-packages/ivre/view.py", line 553, in to_view
    next_recs.append(next(itrs[i]))
  File "/usr/local/lib/python3.7/dist-packages/ivre/view.py", line 517, in from_nmap
    cur_rec = db.view.merge_host_docs(cur_rec, rec)
  File "/usr/local/lib/python3.7/dist-packages/ivre/db/mongo.py", line 1784, in merge_host_docs
    rec = super(MongoDBActive, self).merge_host_docs(rec1, rec2)
  File "/usr/local/lib/python3.7/dist-packages/ivre/db/__init__.py", line 2269, in merge_host_docs
    return merge_host_docs(rec1, rec2)
  File "/usr/local/lib/python3.7/dist-packages/ivre/active/data.py", line 449, in merge_host_docs
    other.setdefault("origins", set()).union(origins)
AttributeError: 'list' object has no attribute 'union'

### Expected behavior

No error.

### Actual behavior

See error above. 

### How to reproduce

See above.

### More

System is a Debian 10 VM with latest patches, Mongo-DB is 4.2.10

**Comment by p-l-** [comment]
Thanks a lot for reporting this. This should be fixed by #1021. Could you apply the patch and confirm?

**Comment by duncrow** [comment]
Hmm, I'm not a git wizard, so I hope I've done everything right with the patch (I'll have more time to test during the weekend.)

New error:
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 95, in <module>
    main()
  File "/usr/local/bin/ivre", line 66, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.7/dist-packages/ivre/tools/db2view.py", line 103, in main
    for elt in itr:
  File "/usr/local/lib/python3.7/dist-packages/ivre/view.py", line 576, in to_view
    next_recs[i] = next(itrs[i])
  File "/usr/local/lib/python3.7/dist-packages/ivre/view.py", line 517, in from_nmap
    cur_rec = db.view.merge_host_docs(cur_rec, rec)
  File "/usr/local/lib/python3.7/dist-packages/ivre/db/mongo.py", line 1784, in merge_host_docs
    rec = super(MongoDBActive, self).merge_host_docs(rec1, rec2)
  File "/usr/local/lib/python3.7/dist-packages/ivre/db/__init__.py", line 2269, in merge_host_docs
    return merge_host_docs(rec1, rec2)
  File "/usr/local/lib/python3.7/dist-packages/ivre/active/data.py", line 503, in merge_host_docs
    merge_scripts(curscript, script, script['id'])
  File "/usr/local/lib/python3.7/dist-packages/ivre/active/data.py", line 377, in merge_scripts
    return merge_http_app_scripts(curscript, script, script_id)
  File "/usr/local/lib/python3.7/dist-packages/ivre/active/data.py", line 284, in merge_http_app_scripts
    http_app_output)
  File "/usr/local/lib/python3.7/dist-packages/ivre/active/data.py", line 355, in _merge_scripts
    if script_equals(to_add, cur, script_id):
  File "/usr/local/lib/python3.7/dist-packages/ivre/active/data.py", line 270, in http_app_equals
    return (a['application'] == b['application'] and
TypeError: string indices must be integers

**Comment by p-l-** [comment]
Could you run the following command:
```
$ python -i `which ivre` db2view nmap
```
Then when the crash comes, you get a Python prompt:
```
>>> from pdb import pm
>>> pm()
>>> print(repr(a))
[ please report the output here ]
>>> print(repr(b))
[ please report the output here ]
```

**Comment by p-l-** [comment]
Also, that's not related to this bug but you seem to have records from schema versions lower than the current one, so you might want to upgrade them:
```
ivre scancli --update-schema
```

**Comment by p-l-** [comment]
OK I **think** I found the second bug (which is unrelated). Bad news is: the fix will not fix your current data. Good news is, when you have applied the patch in #1022, you can run the following Python script to fix your data:

```Python
from ivre.db import db

for dbase in [db.nmap, db.view]:
    for host in dbase.get(dbase.searchhttpapp(name="SharePoint")):
        changed = False
        for port in host.get('ports', []):
            for script in port.get('scripts', []):
                if script['id'] == 'http-app' and isinstance(script.get('http-app'), dict):
                    script['http-app'] = [script['http-app']]
                    changed = True
        if changed:
            dbase._migrate_update_record(
                dbase.columns[dbase.column_hosts],
                host['_id'],
                {"$set": {"ports": host['ports']}},
            )
```

**Comment by duncrow** [comment]
Sorry for the delay. I applied your patch, works like a charm, problem went away. Also ran your script to fix up my data, ran without a problem.

Thank you very much for your quick response & fix!
