### ISSUE TITLE
Connect Zeek with my docker instance of ivre/web

### ISSUE THREAD

**Issue by acj014** [cea-sec/ivre#1027]
### IVRE Version -> https://hub.docker.com/r/ivre/web

Hello together,

when i try to connect zeek with my docker instance of ivre/web i try

root@kali:/usr/local/zeek/bin# ./zeek -b /var/lib/docker/overlay2/3fc373f9fa2f3a1c5e38bc4641efd1c90b3e576126fcbb2db452259296b8404e/merged/usr/local/share/ivre/zeek/ivre/passiverecon/bare.zeek >   ivre passiverecon2db
fatal error: can't find passiverecon2db

As you can see i cannot find the database, what can i do ? 
Im still really unexperienced with this software, please be patient.

Thanks for any help!

$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.15

Python 3.8.2 (default, Feb 26 2020, 22:21:03)
[GCC 9.2.1 20200130]

Linux computer 5.6.6-arch1-1 #1 SMP PREEMPT Mon, 30 Mar 2020 20:42:41 +0000 x86_64

Dependencies:
    Python module pymongo: 3.10.1
    [...]
```

### Summary

Short summary.

### Expected behavior

Describe here what you would expect, if the feature you want existed,
or if the bug you report didn't exist.

### Actual behavior

If needed, describe what actually happens. Be sure to include
comprehensive output, including obscure error messages, logs from the
Web or DB server if appropriate, etc.

### How to reproduce

If needed, include the exact commands others can try to reproduce your
issue.

### More

Please include any other information that could help us, including
scan results or PCAP samples. We will be able to help you faster if we
don't have to ask questions and wait for your answers.

**Comment by p-l-** [comment]
Hi there!

It seems to me that you probably have more a Docker issue than an IVRE issue... for now!

You should probably use the `ivreclient` container and copy the `/usr/local/share/ivre/zeek` to the shared directory (`ivre-share` if you use the `Vagrantfile`), and use it from the computer from there.

`zeek` will the produce `passiverecon` logs that you will have to parse from the `ivreclient` instance (using `ivre passiverecon2db`).

If you have troubles using IVRE with Docker, maybe you should install IVRE on your computer to limit this kind of issues?

**Comment by acj014** [comment]
Thanks for the fast response, maybe can we use some chat for a better help, i would be really thankful as i am not that experienced.
My goal is to Threat Hunt my Home network especially the IOT devices for my university project.

**Comment by p-l-** [comment]
That's more a zeek issue now. You need to tell zeek what network it should sniff (add `-r capture_file.pcap` or `-i interface_name` for example to your zeek command line).

**Comment by p-l-** [comment]
If you need a chat, you can join https://gitter.im/cea-sec/ivre.

**Comment by p-l-** [comment]
We're tracking this on the chat so I'm closing this issue.
