### ISSUE TITLE
How do I set ports in NMAP_SCAN_TEMPLATES by Python API?

### ISSUE THREAD

**Issue by ubushan** [cea-sec/ivre#1028]
```
IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.15.dev156

Python 2.7.17 (default, Sep 30 2020, 13:38:04)
[GCC 7.5.0]

Linux Bender 5.4.0-1031-azure #32~18.04.1-Ubuntu SMP Tue Oct 6 10:03:22 UTC 2020 x86_64

Dependencies:
    Python module pymongo: 3.11.0
    Python module sqlalchemy: 1.3.20
    Python module psycopg2: 2.7.4 (dt dec mx pq3 ext lo64)
    Python module cryptography: 2.4.2
    Python module krbV: [unknown version]
    Python module PIL: 5.1.0
    Python module MySQLdb: 1.3.10
    Python module dbus: 1.2.6
    Python module matplotlib: 2.2.5
    Python module bottle: 0.12.18
    Python module OpenSSL: missing
    Python module tinydb: 3.15.2
    [...]
```

Tell me please, how do I set ports in NMAP_SCAN_TEMPLATES by Python API?
I tried like this `python -c "from ivre import config; config.NMAP_SCAN_TEMPLATES['my_template'].update({'ports':'80,443'})"` but it doesn't apply.

Thanks!

**Comment by p-l-** [comment]
You need to create (or update) a file that can be either `/etc/ivre.conf` (system-wide) or `~/.ivre.conf` (user-specific).

Another option is to create an arbitrary file and use it by setting the `IVRE_CONF` environment variable (`IVRE_CONF=/path/to/file ivre [...]`).

**Comment by ubushan** [comment]
@p-l- thanks a lot for the answer. 
Yes, I know about this conf file `/etc/ivre.conf` and I update this file manualy when I need it. But I would update conf file by PythonAPI or WebAPI for scripts. Now I use `sed` for update ivre.conf, but it temporary solution.

**Comment by p-l-** [comment]
I have no other solution to offer. If you **really** need to update the configuration from a script, I **think** you can:
* import the config sub-module,
* change the values as you need,
* only then import other IVRE sub-modules.

**Comment by ubushan** [comment]
What is config sub-module?

**Comment by p-l-** [comment]
`ivre.config`

**Comment by ubushan** [comment]
Okey, thanks a lot!
