### ISSUE TITLE
WebAPI don't work

### ISSUE THREAD

**Issue by ubushan** [cea-sec/ivre#1029]
```
IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.15.dev156

Python 2.7.17 (default, Sep 30 2020, 13:38:04)
[GCC 7.5.0]

Linux Bender 5.4.0-1031-azure #32~18.04.1-Ubuntu SMP Tue Oct 6 10:03:22 UTC 2020 x86_64

Dependencies:
    Python module pymongo: 3.11.0
    Python module sqlalchemy: 1.3.20
    Python module psycopg2: 2.7.4 (dt dec mx pq3 ext lo64)
    Python module cryptography: 2.4.2
    Python module krbV: [unknown version]
    Python module PIL: 5.1.0
    Python module MySQLdb: 1.3.10
    Python module dbus: 1.2.6
    Python module matplotlib: 2.2.5
    Python module bottle: 0.12.18
    Python module OpenSSL: missing
    Python module tinydb: 3.15.2
    [...]
```

Hello! I need help. 
WebAPI don't work. What am I doing wrong? Previously IVRE WebAPI did not use.
Thanks!
![Screenshot 2020-11-17 164104](https://user-images.githubusercontent.com/12890432/99397151-babc5200-28f3-11eb-8d4e-216f24783318.png)

**Comment by p-l-** [comment]
You cannot hit `/cgi/views/*`, it does not exsist. You could hit, for example `/cgi/view`, or `/cgi/view?q=80` (to get results with port TCP/80 open).

**Comment by ubushan** [comment]
@p-l- thanks for the answer.
I get this message
```$ curl http://127.0.0.1:80/cgi/view?q=80
try {add_message("referer", "error", "Invalid Referer header. Check your configuration.");}
catch(err) {alert("ERROR: Invalid Referer header. Check your configuration.");}```

**Comment by p-l-** [comment]
As the message says, you need to set a Referer header (this is for CSRF prevention): `curl -e http://127.0.0.1:80/ http://127.0.0.1:80/cgi/view?q=80` should work (with the default configuration).

**Comment by ubushan** [comment]
But how? There is no reverse proxy on my computer. I tried changing the domain "reverse-proxy.local" to "localhost" and "127.0.0.1" in ivre.conf and nothing helped solve this problem.
```
...
WEB_ALLOWED_REFERERS = [
    'http://127.0.0.1/ivre',
    'http://127.0.0.1/ivre/',
    'http://127.0.0.1/ivre/index.html',
    'http://127.0.0.1/ivre/report.html',
    'http://127.0.0.1/ivre/upload.html',
    'http://127.0.0.1/ivre/compare.html',
    'http://127.0.0.1/ivre/flow.html'
]
...
```

**Comment by p-l-** [comment]
Without changing the configuration, does the command `curl -e http://127.0.0.1:80/ http://127.0.0.1:80/cgi/view?q=80` work?

**Comment by ubushan** [comment]
```
$ curl -e http://127.0.0.1:80/ http://127.0.0.1:80/cgi/view?q=80
try {add_message("referer", "error", "Invalid Referer header. Check your configuration.");}
catch(err) {alert("ERROR: Invalid Referer header. Check your configuration.");}
```

**Comment by p-l-** [comment]
OK, Try simply: `curl -e http://127.0.0.1/ http://127.0.0.1/cgi/view?q=80`

**Comment by ubushan** [comment]
`curl -e http://127.0.0.1/ http://127.0.0.1/cgi/view?q=80` It works.
