### ISSUE TITLE
help me!

### ISSUE THREAD

**Issue by agnousse** [cea-sec/ivre#103]
Bonsoir Pierre ,
j'ai installé le framework sur un de mes serveurs distants, tout semble nominal 
interface Web ok, scan actif ok .
En suivant ta procedure et doc : 
"If you access the web interface by another URL than the "standard"
<http://localhost/>, then you have to set `ALLOWED_REFERERS` in
`scanjsonconfig.py`"
je me suis mis à la recherche du fichier pour modif, je ne l'ai pas trouvé. je pense être passé à côté d'un truc :( 
as tu une idée ? par avance merci
@gn0u$$e (David)

**Comment by agnousse** [comment]
heu je vais boire une bière à ta santé car super boulot , énorme !!
@gn0u$$e

**Comment by p-l-** [comment]
Salut, c'est dans la version actuelle ça ? Parce que normalement ce n'est plus le cas, `ALLOWED_REFERERS` ne devrait être touché que dans des configurations particulières (reverse-proxy essentiellement). Pour la prochaine issue, tu fais en anglais histoire que tout le monde puisse en profiter ?

**Comment by agnousse** [comment]
Thank you, I take with the doc to date!
@gn0$$e
