### ISSUE TITLE
Suggest to use rustscan instead of masscan

### ISSUE THREAD

**Issue by highkay** [cea-sec/ivre#1038]
As masscan is inactive developing, suggest to use [RustScan](https://github.com/RustScan/RustScan), it is also worked well with nmap.

**Comment by p-l-** [comment]
Hi,

Thanks for your suggestion.

I don't think Masscan development is inactive, plus I recommend the use of [IVRE's fork](https://github.com/ivre/masscan) (which is still under active development). Also, I don't see (for now) what problem RustScan attempts to solve. However, if you want to describe a use case (for example) that uses IVRE and relies on RustScan, of course, I'll be very to have a look at it, and integrate it if it does bring something helpful.

All the best,

Pierre
