### ISSUE TITLE
Nmap option --top-ports usage with runscan

### ISSUE THREAD

**Issue by Amadimk** [cea-sec/ivre#1041]
Hello,

How can I use nmap option --top-ports instead ports setting to perform runscan with nmap.

eg: i want to run my scan with this nmap command line.

nmap -sC -sV --top-ports 100  x.x.x.x

how i can set my nmap config file to do that.

Thank you.

**Comment by p-l-** [comment]
Hi,

I'm sorry but the answer is... you cannot. The quick & dirty way to do it would be to patch `ivre/nmapopt.py`. The correct way to do it would be to create a pull request to make it configurable.

I'll leave this issue open so that someone can implement it (maybe you?).

**Comment by Amadimk** [comment]
Thank you for your answer.

I implemented my own solution, I will create a pull request of my solution.
