### ISSUE TITLE
[Feature Request] - Results - Increase the amount of results to show 50,100,250

### ISSUE THREAD

**Issue by aryanguenthner** [cea-sec/ivre#1098]
![image](https://user-images.githubusercontent.com/5551660/113441460-36023a00-93a3-11eb-81ae-f88c8b9a7648.png)

### IVRE Version
IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.16

Insert here the output of the command `ivre version`, displayed as
code. For example:

**Comment by p-l-** [comment]
Just add `limit:100` (see [the documentation](https://doc.ivre.rocks/en/latest/usage/web-ui.html#sort))
