### ISSUE TITLE
Help setting up a new IVRE server

### ISSUE THREAD

**Issue by samtuke** [cea-sec/ivre#1110]
Hi All, does anyone provide pro help setting up & maintaining IVRE? I'd like to discuss help with that if you do. Thanks!

**Comment by p-l-** [comment]
"pro": do you mean commercial support? If so, I don't think so. You can chat on [Giiter](https://gitter.im/cea-sec/ivre) if you have specific questions.
Please re-open if I have misunderstood your question.
