### ISSUE TITLE
Raspberry pi 4 Ubuntu 64bit Flow Timeline Issue

### ISSUE THREAD

**Issue by jimthedj65** [cea-sec/ivre#1113]
Please try to follow this template. Also, please format your issue
properly (particularly to report code or command line output). You may
want to read
[Github's basic writing and formatting syntax](https://help.github.com/articles/basic-writing-and-formatting-syntax/).

### IVRE Version

Latest version since 18-04-2021

```
IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.16.dev168

Python 3.8.6 (default, Jan 27 2021, 15:42:20)
[GCC 10.2.0]

Linux netscan 5.8.0-1021-raspi #24-Ubuntu SMP PREEMPT Tue Apr 13 11:00:57 UTC 2021 aarch64

Dependencies:
    Python module pymongo: 3.10.1
    Python module sqlalchemy: 1.4.9
    Python module psycopg2: missing
    Python module cryptography: 3.0
    Python module krbV: missing
    Python module PIL: 8.2.0
    Python module MySQLdb: missing
    Python module dbus: 1.2.16
    Python module matplotlib: 3.4.1
    Python module bottle: 0.12.15
    Python module OpenSSL: 19.1.0
    Python module tinydb: missing
```

### Summary

Short summary.

### Expected behavior

I expect the input capture to playback a timeline in the flow part of the web UI

### Actual behavior

All the data loads and displays properly, see an image attached of status.  I seem to have a missing max time slot in the timeline settings.

### How to reproduce
Import data from Wireshark with various formats and saved files and it won't recognize a timeline.
issue.

### More

Running on a raspberry pi4 with ubuntu 64 bit, everything else is running as expected.
<img width="1574" alt="Screenshot 2021-04-18 at 17 47 37" src="https://user-images.githubusercontent.com/46975497/115154167-63bcd380-a071-11eb-8d65-20f1606ce28c.png">

**Comment by p-l-** [comment]
Hi,

Thanks for using IVRE!

It looks like your capture did not last long enough to cover several time slots.

The `FLOW_TIME_PRECISION` configuration variable defaults to 3600, so you need to capture for more than one hour. You can reduce this value (in `/etc/ivre.conf`), re-initialize the flow database and import your results again, or you can capture more data.

Let us know if that hypothesis is correct or if we need to find another explanation.

**Comment by jimthedj65** [comment]
Thanks for the tool, I looked at this way back a few years ago and glad to see it has evolved.  I am having some fun and plan to use it for network analysis from a GRE to ERSPAN capture and write an import tool to import every 5 minutes.  ahh that makes sense now thanks I did capture for 20 minutes or so.  I will run a capture for one hour and report back here.

**Comment by jimthedj65** [comment]
Thanks for the tool, I looked at this way back a few years ago and glad to see it has evolved.  I am having some fun and plan to use it for network analysis from a GRE to ERSPAN capture and write an import tool to import every 5 minutes.  ahh that makes sense now thanks I did capture for 20 minutes or so.  I will run a capture for one hour and report back here.

**Comment by jimthedj65** [comment]
sorry closed it by mistake

**Comment by jimthedj65** [comment]
Hi @p-l-  that was exactly the problem I reduced the time down to a smaller increment and reinitialised and the timeline plays back great now.  thanks for the help, very much appreciated.

**Comment by jimthedj65** [comment]
just one question when I click on the pencil top right of an item search listing I get 

Forbidden
You don't have permission to access this resource.

Apache/2.4.46 (Ubuntu) Server at 192.168.x.xx Port 80

any idea what that could be? is it possible permissions are not set correctly somewhere?
<img width="671" alt="Screenshot 2021-04-20 at 11 03 49" src="https://user-images.githubusercontent.com/46975497/115378442-7695ec00-a1c8-11eb-96d6-67b002b48f8e.png">

**Comment by p-l-** [comment]
You need to configure your Dokuwiki to accept connexions from other IP addresses than 127.0.0.1. See #320.

**Comment by jimthedj65** [comment]
hi @p-l- thanks
