### ISSUE TITLE
Support Cloud MongoDB connection method

### ISSUE THREAD

**Issue by shinegod** [cea-sec/ivre#1121]
Can you support cloud Mongodb Connection method?

Goole cloud,azure,aws,ali cloud

mongodb://ivre:xxxxxxxxxxx@ivre.mongo.cosmos.azure.com:1111/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@ivre@"

mongodb+srv://xxxxxxxx:123321@cluster0-jarma.azure.mongodb.net/test?retryWrites=true&w=majority

**Comment by p-l-** [comment]
Hi,

I have no such access to test that kind of connection. I will leave this issue open so that someone can implement it.
