### ISSUE TITLE
--no-merge argument not working

### ISSUE THREAD

**Issue by nothimofc** [cea-sec/ivre#1614]
https://github.com/ivre/ivre/blob/9a4f7ff7a07870d4743381c3b229cc45c5c26f40/ivre/tools/db2view.py#L102

The --no-merge argument isn't working, it still merges the two results that have different hosts and different sources into one result.

**Comment by p-l-** [comment]
What do you mean different host? Different IP address? Could you share a minimum set of results that highlight the bug?

**Comment by p-l-** [comment]
Yeah the `--no-merge` option means "do not merge with existing results **in view**" not "with other results you are currently adding".

**Comment by p-l-** [comment]
Not with the current code base. It should need a bit of code change to match your expectations.
What you **could** do if you want to keep the current code is identity a field on which you want to merge results. For example, say a given category (could work with a source too).
1. You use that category to tag your results on `scan2db` (say `ivre scan2db -c SCAN,SCAN01 [...]` then `ivre scan2db -c SCAN,SCAN02 [...]`, etc.
2. You run several `db2merge --no-merge` (for example `ivre db2view --category SCAN01 --no-merge`, `ivre db2view --category SCAN02 --no-merge`, etc.)
Then you should have in your view results for `SCAN01` in different records than those for `SCAN02`.
Does it make sense?
