### ISSUE TITLE
[Bug] Filter parsing doesn't work on Firefox 41

### ISSUE THREAD

**Issue by commial** [cea-sec/ivre#165]
Using last IVRE version (5bb541b) and Firefox 41.0.1, adding a second filter through the web interface ends with a unique, broken filter `filter1%20filter2`.

It may be related with `document.location.hash` returning `filter1%20filter2` on Firefox, contrary of `filter1 filter2` on Chrome.

**Comment by p-l-** [comment]
Thanks. This is related to a change in the latest Firefox version. For reference: https://www.fxsitecompat.com/en-US/docs/2015/urlutils-hash-no-longer-decodes-fragment/.
