### ISSUE TITLE
 global name 'sys' is not defined

### ISSUE THREAD

**Issue by tobor** [cea-sec/ivre#173]
WARNING, script element without port or host
WARNING, script element without port or host
Warning:guessing pitch as xheight on row 1, block 2
WARNING, script element without port or host
WARNING, script element without port or host
WARNING, script element without port or host
Traceback (most recent call last):
  File "/usr/local/bin/nmap2db", line 118, in <module>
    main()
  File "/usr/local/bin/nmap2db", line 114, in main
    sys.stderr.write(ivre.utils.warn_exception(exc, fname=scan))
NameError: global name 'sys' is not defined

**Comment by p-l-** [comment]
Thanks! That should be fixed now.
