### ISSUE TITLE
Http-screenshot to FQDN instead of IP address.

### ISSUE THREAD

**Issue by fjavierc** [cea-sec/ivre#178]
Hello!

Is it possible to make a http-screenshot to a FQDN instead of IP address ?

Many websites resolve to the same ip address and when I do a "http-screenshot" to a FQDN,  it attacks the IP address and get errors 403 - Access Denied.

To make the http-screenshot I use phantomjs, screenshot.js and http-screenshot.nse from Ivre repository and works ok.

Thanks!

**Comment by p-l-** [comment]
Hi,

Can you check if the patch form #180 works for you? Thanks!

**Comment by fjavierc** [comment]
Hi Pierre,

Work OK  !!

Well ... except when there is some automatic redirection ( HTTP 302 code ) or when trying to make a screenshot over HTTPS ( port 443, 8443, etc ).  I think this "problem" is more complicated to resolve or need more extensive development.

What do you think ? Do you think is better to open a new issue/enhancement ?

Thank you!

**Comment by p-l-** [comment]
Do you have an example of web site you cannot screenshot? Since this fixes the problem reported I'll merge #180 (which will close this issue), open another one to report sites for which the script fails. Thanks again!
