### ISSUE TITLE
How do you update an existing docker client?

### ISSUE THREAD

**Issue by mw3demo** [cea-sec/ivre#188]
Hey there!

Not directly related to ivre, but I am not very experienced with docker. How do I update ivre from within the container? Is there a way for it to update as and when updates are pushed to github on my machine?

I have a bunch of data in the container I don't want to loose, but not sure what the upgrade path method is.

**Comment by p-l-** [comment]
Normally (i.e., if you have followed the instructions from the [documentation](../tree/master/doc/DOCKER.md)), your data should not be in the container but in a volume.

This means you can safely destroy your containers (**check you can access your data from outside the container before any manipulation**), the images, upgrade the images and run the containers again.

If for some reason your data is only accessible from the container, use `docker` commands to copy the files under `/var/lib/mongodb` to your host (please refer to Docker documentation on how to do that).

**Comment by p-l-** [comment]
Sorry, I have closed this issue inadvertently, feel free to comment here anyway if you want/need, or to close it if the answer works for you.

**Comment by mw3demo** [comment]
Hey p-i-,

Sorry for the late reply, all working on my end and many thanks for the confirmation. Have a good weekend.

**Comment by p-l-** [comment]
Perfect, thanks!
