### ISSUE TITLE
Can't Get IP data

### ISSUE THREAD

**Issue by Xmansec** [cea-sec/ivre#211]
Hey, even if I run this command(ipdata --download) more than one day, it still does not have any output, I have to press Ctrl-C to stop it. Is there any other way to replace this command?

**Comment by p-l-** [comment]
Hi,

Can you check (e.g., with `tcpdump`) whether or not a download is occurring? Can you run `ls -l /usr/share/ivre/geoip/` (or `/usr/share/local/ivre/geoip`, depending on where IVRE has been installed)?

**Comment by Xmansec** [comment]
I reinstall the IVRE, and then the problem is solved.Thanks!
