### ISSUE TITLE
HES2015 slides

### ISSUE THREAD

**Issue by izeau** [cea-sec/ivre#216]
Hi guys,

I’m interested in your software and it seems you’ve presented it at the HES2015 conf. However, the slides [don’t seem to be available yet](http://2015.hackitoergosum.org/slides/); could you maybe share them somewhere?

Cheers!

**Comment by p-l-** [comment]
Up @commial

**Comment by fjavierc** [comment]
Hi all

Izeau, maybe late but ... you can watch the  talk and presentation on youtube

- HXXPS://www.youtube.com/watch?v=FC6WfNBAuCM

(  HES2015 "Applying machine learning methods network mapping" by Camille Mougey & Xavier Martin;  )

**Comment by izeau** [comment]
That’s great, thank you very much!
