### ISSUE TITLE
Installation through pip doesn't handle directories creation correctly

### ISSUE THREAD

**Issue by CyrilleFranchet** [cea-sec/ivre#225]
Hi,

It seems that pip doesn't create the /usr/local/share/ivre/geoip/ directory under Debian. Due to this problem check_candidate in config.py is not able to locate the folder automatically and GEOIP_PATH is set to None.

Furthermore, the setup.py file in pip package (version 0.9.3) is different from the file on GitHub. Is it a good thing?

I don't really understand pip packaging so I let you think about it :)

Cyrille

**Comment by p-l-** [comment]
Hi,

Thanks for this! The version on Github is more up-to-date than on PyPI. About the directory creation, I'll have a look!

**Comment by p-l-** [comment]
From my latest tests, this has been fixed. Feel free to re-open if that's not the case.
