### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by vxnuke** [cea-sec/ivre#226]
I followed https://github.com/cea-sec/ivre/blob/master/web/dokuwiki/doc/fast-install-and-first-run.txt and got this error

root@server:~# ivre ipdata --download
Downloading http://geolite.maxmind.com/download/geoip/database/GeoLiteCity_CSV/GeoLiteCity-latest.zip to /usr/local/share/ivre/geoip/GeoIPCityCSV.zip: done.
Downloading http://thyme.apnic.net/current/data-raw-table to /usr/local/share/ivre/geoip/BGP.raw: done.
Downloading http://geolite.maxmind.com/download/geoip/database/asnum/GeoIPASNum2.zip to /usr/local/share/ivre/geoip/GeoIPASNumCSV.zip: done.
Downloading http://geolite.maxmind.com/download/geoip/database/GeoIPCountryCSV.zip to /usr/local/share/ivre/geoip/GeoIPCountryCSV.zip: done.
Unpacking: Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 73, in <module>
    main()
  File "/usr/local/bin/ivre", line 51, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/ipdata.py", line 95, in main
    ivre.geoiputils.download_all(verbose=not args.quiet)
  File "/usr/local/lib/python2.7/dist-packages/ivre/geoiputils.py", line 161, in download_all
    func(*args, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/ivre/geoiputils.py", line 81, in bgp_raw_to_csv
    utils.net2range(line[:-1].split()[0]))
  File "/usr/local/lib/python2.7/dist-packages/ivre/utils.py", line 93, in net2range
    addr, mask = network.split('/')
ValueError: need more than 1 value to unpack

**Comment by p-l-** [comment]
Hi,

I cannot reproduce this. Is this somehow related to #235?

If you still have this issue, can you provide the content of `/usr/share/ivre/geoip/BGP.*`?

**Comment by vxnuke** [comment]
IVRE installs fine now. I'm guessing it was somehow related to #235
