### ISSUE TITLE
Dokuwiki frame forbidden

### ISSUE THREAD

**Issue by powerhikki** [cea-sec/ivre#239]
Hi,

After fast installation using manual I cannot access to dokuwiki in HELP menu. Apache2 says 

```
Forbidden
You don't have permission to access /dokuwiki/doc:webui on this server.
```
Linux debian 4.5.5-x86_64-linode69 #3 SMP Fri May 20 15:25:13 EDT 2016 x86_64 GNU/Linux

Server version: Apache/2.4.10 (Debian)
Server built:   Nov 28 2015 14:05:48

Thanx.

**Comment by p-l-** [comment]
You must configure Apache so that dokuwiki is accessible from your client.
