### ISSUE TITLE
Handling objects returned by 'topvalues'

### ISSUE THREAD

**Issue by Hadnap** [cea-sec/ivre#242]
When using a criteria that makes the _topvalues_ function return an object as the label, the graph displays "[object Object]" instead of the value/string.

For instance, the 'openports' criteria.

**Comment by p-l-** [comment]
Actually, the correct way to get the most common open ports is to use `ports:open`. This will use the `openports` attribute and handle the output. Does it work for you?

**Comment by p-l-** [comment]
Closing after discussion with @Hadnap.
