### ISSUE TITLE
Problems with aggregate method and its parameters

### ISSUE THREAD

**Issue by Yiazmat01** [cea-sec/ivre#271]
I have installed ivre by following the fast install guide. Globally the framework runs fine nevertheless I have some trouble using some features :
- no map in webui;
- no top ports in webui and scancli;
- analyzercli not running.

All those problems seem to be linked with the `cursor` parameter when calling `aggregate` method in `mongo.py` and `analyzer.py` files. There are also problems with the pipeline parameters which contains unrecognized field.

As a temporary workaround I have removed `cursor={}` parameter in all `aggregate` methods. It fixes some features like map display in webui but there are still pipeline linked errors. I have not investigated deeper for the moment.

Here are some of my error outputs :
 - Before workaround

`>>> db.nmap.topvalues('portlist:open')`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/usr/local/lib/python2.7/dist-packages/ivre/db/mongo.py", line 2340, in topvalues`
`    self.db[colname].aggregate(pipeline, cursor={})`
`  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1680, in aggregate`
`    result = self._command(sock_info, cmd, slave_ok)`
`  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 208, in _command`
`    read_concern=read_concern)`
`  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 239, in command`
`    read_concern)`
`  File "/usr/local/lib/python2.7/dist-packages/pymongo/network.py", line 102, in command`
`    helpers._check_command_response(response_doc, None, allowable_errors)`
`  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 205, in _check_command_response`
`    raise OperationFailure(msg % errmsg, code, response)`
`pymongo.errors.OperationFailure: unrecognized field "cursor`

- After the workaround 

`>>> db.nmap.topvalues('portlist:open')`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/usr/local/lib/python2.7/dist-packages/ivre/db/mongo.py", line 2341, in topvalues`
`    )`
`  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1680, in aggregate`
`    result = self._command(sock_info, cmd, slave_ok)`
`  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 208, in _command`
`    read_concern=read_concern)`
`  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 239, in command`
`    read_concern)`
`  File "/usr/local/lib/python2.7/dist-packages/pymongo/network.py", line 102, in command`
`    helpers._check_command_response(response_doc, None, allowable_errors)`
`  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 205, in _check_command_response`
`    raise OperationFailure(msg % errmsg, code, response)`
`pymongo.errors.OperationFailure: exception: Unrecognized pipeline stage name: '$redact'`

**Comment by p-l-** [comment]
Hi,

Can you report here the version of PyMongo you are using (you can run `python -c 'print __import__("pymongo").__version__'`?

Thanks!

**Comment by Yiazmat01** [comment]
Hi,

Here are my outputs :

`$ python -c 'print __import__("pymongo").__version__'`
`3.3.0`
`$ mongod --version`
`db version v2.4.14`

**Comment by p-l-** [comment]
As stated both in [doc/README.md](https://github.com/cea-sec/ivre/blob/master/doc/README.md) and in [doc/FAST-INSTALL-AND-FIRST-RUN.md](https://github.com/cea-sec/ivre/blob/master/doc/FAST-INSTALL-AND-FIRST-RUN.md), you should use at least MongoDB 2.6 (and I would recommend more recent).

Can you upgrade your MongoDB installation and report here whether that fixes your problems? Thanks!

**Comment by Yiazmat01** [comment]
Everything seems working fine now. I'll try to read more carefully next time.

Thank you for you quick answers.

**Comment by p-l-** [comment]
Thanks! I'm glad it works for you now, and hope you'll have fun with IVRE!

Don't hesitate to contact us if you have any other question or problem.
