### ISSUE TITLE
Some questions about PassiveRecon

### ISSUE THREAD

**Issue by fjavierc** [cea-sec/ivre#283]
Hi everybody!

Now that I have a little more free time I am working with IVRE and seeing the possibility of using their full potential and if I can, I want to add some code to my IVRE setup so that it can cover other needs (actually some lines of code)

Well, now I'm trying Bro and PassiveRecon and I have some questions about it.

- When I run "_bro /usr/local/share/ivre/passiverecon/passiverecon.bro -b -i eth0 | ivre passiverecon2db_", where the data is stored?

- The data collected by Bro and  processed by passiverecon2db, are saved in real time? and rotate ?

It happens that after a few days Bro & Passiverecon2db stops working; I have to kill processes and re-launch. Any ideas ?.  It's something I do not worry much since I have this automated :-p

On the other hand, I would like (well, I'm on it), try to store the information collected by Bro in Elasticsearch but plugin's Bro only supports Elasticsearch V1. Does anyone have something done or can give me some tips?

Thanks!

**Comment by p-l-** [comment]
The data is stored in the MongoDB database, in a dedicated collection. There is no "rotation": each new piece of information is stored forever, with three fields that will evolve each time it is seen again: `firstseen`, `lastseen` and `count`.
Regarding elasticsearch, no idea. Maybe you should ask the Bro community?

**Comment by p-l-** [comment]
Feel free to comment and reopen this issue if this does not totally answer your question.
