### ISSUE TITLE
remote agent I/O error

### ISSUE THREAD

**Issue by nirhenn** [cea-sec/ivre#284]
Hi there,

I am working on setting up remote agent and performs remote scans.
The env i have has ssh sync none interactive and working rsync.
when i send the following
sudo ivre runscansagentdb --assign-free-agents -r 10.0.0.253 10.0.0.253

ubuntu@ivre:~$ 
ubuntu@ivre:~$ sudo ivre runscansagentdb --daemon
on the agent side :
[worker 8   ] scan 57b0719953618d7e0c2df7ec-abG8_O
[worker 8   ] done 57b0719953618d7e0c2df7ec-abG8_O

But after a while when the scan is done i get:

bzcat: I/O or other error, bailing out.  Possible reason follows.
bzcat: Broken pipe
	Input file = /var/lib/ivre/master/output/57b0719953618d7e0c2df7ec/57b0719153618d7de440a49f/5W_SXp.xml, output file = (stdout)
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 73, in <module>
    main()
  File "/usr/local/bin/ivre", line 51, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/runscansagentdb.py", line 224, in main
    ivre.db.db.agent.sync_all(masterid)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 910, in sync_all
    self.sync(agentid)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 959, in sync
    source=agent['source'],
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 339, in store_scan
    raise ValueError("Unknown file type %s" % fname)
ValueError: Unknown file type /var/lib/ivre/master/output/57b0719953618d7e0c2df7ec/57b0719153618d7de440a49f/5W_SXp.xml

**Comment by p-l-** [comment]
Sounds odd... can you attach the file causing the issue?

**Comment by nirhenn** [comment]
I had to compress the file in order to attach it.

[5W_SXp.xml.zip](https://github.com/cea-sec/ivre/files/421821/5W_SXp.xml.zip)

**Comment by p-l-** [comment]
I don't know what your agent does exactly, but it has created a file with data before the XML output:
```
***********************************************
nmap -A -PS -PE -vv --host-timeout 15m -sS -sU -p T:-,U:161 --top-ports 1000 --script=(default or discovery or auth) and not (broadcast or brute or dos or expl
oit or external or fuzzer or intrusive) or snmp-sysdescr or snmp-brute or snmp-interfaces or snmp-ios-config -iL - -oX -
```
IVRE does not know what to do with that. You have to fix your agent to prevent it from adding those lines.
Please report here when/if it works or if you cannot fix it.
