### ISSUE TITLE
How screenshot are inserted into DB?

### ISSUE THREAD

**Issue by CyrilleFranchet** [cea-sec/ivre#288]
Hi,

I'm trying to understand why screenshots are no more inserted into DB. I read xmlnmap.py and I don't understand the following code
```
if ignore_script(self._curscript):
                self._curscript = None
                return
```
This block happens before you work on the screenshot section and http-screenshot is marked as an ignored script. So self._curscript seems to be set to None before the screenshot is evaluated.

I may have misunderstood the whole code but I think that commit [f6d799a](https://github.com/cea-sec/ivre/commit/f6d799a02733c06463d78a434a5c27ae0b10ab8d#diff-da82567b9639eed9bbb7bb9f4e8b9078) have broken the screenshot feature.

Thanks.

**Comment by key134** [comment]
You're right. It does entirely ignore the screenshot script. I rolled back that commit and my screenshots started working. I thought my issue was something else, but it was this.

**Comment by p-l-** [comment]
Can you try to replace `IGNORE_SCRIPTS_IDS = set(["http-screenshot"])` by `IGNORE_SCRIPTS_IDS = set([])` in `xmlnmap.py` and tell me whether:
  - the screenshots are imported, and
  - the script "http-screenshot" is correctly ignored (no output for this script exists in the Web interface)?

**Comment by CyrilleFranchet** [comment]
Unfortunately not. Screenshot is correctly imported but we get script output.

**Comment by p-l-** [comment]
OK, so can you check if patch proposed in #291 works?
