### ISSUE TITLE
sudo vagrant up --no-parallel Fails for  Unable to find image 'ivre/db:latest' locally

### ISSUE THREAD

**Issue by qwaszx1** [cea-sec/ivre#366]
zpp@ubuntu:~$ sudo vagrant up --no-parallel
[sudo] zpp 的密码： 
Bringing machine 'ivredb' up with 'docker' provider...
Bringing machine 'ivreweb' up with 'docker' provider...
Bringing machine 'ivreclient' up with 'docker' provider...
==> ivredb: Creating the container...
    ivredb:   Name: ivredb
    ivredb:  Image: ivre/db
    ivredb: Volume: /home/zpp/var_lib_mongodb:/var/lib/mongodb
    ivredb: Volume: /home/zpp/var_log_mongodb:/var/log/mongodb
    ivredb: Volume: /home/zpp/var_lib_neo4j:/var/lib/neo4j/data
    ivredb: Volume: /home/zpp/var_log_neo4j:/var/log/neo4j
A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

Command: ["docker", "run", "--name", "ivredb", "-d", "-v", "/home/zpp/var_lib_mongodb:/var/lib/mongodb", "-v", "/home/zpp/var_log_mongodb:/var/log/mongodb", "-v", "/home/zpp/var_lib_neo4j:/var/lib/neo4j/data", "-v", "/home/zpp/var_log_neo4j:/var/log/neo4j", "ivre/db", {:notify=>[:stdout, :stderr]}]

Stderr: Unable to find image 'ivre/db:latest' locally
/usr/bin/docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout.
See '/usr/bin/docker run --help'.

Stdout:

**Comment by p-l-** [comment]
Hi,

Looks like you cannot download images from Docker repository. This might be a permanent or a temporary error, so you might want to try again later. Also, you can try to download the docker images from the `docker` CLI, maybe the error would be more helpful: `docker pull ivre/db` in this case.
