### ISSUE TITLE
 CGI configuration problem

### ISSUE THREAD

**Issue by c0rpse** [cea-sec/ivre#374]
How should i configure the cgi environment? I use nginx as the web server and spawn-fcgi as the cgi server.But when i start one cgi file like ivre/web/cgi-bin/jsconfig.py,it showes below:
![image](https://cloud.githubusercontent.com/assets/16606443/25303199/b060eb86-2780-11e7-9261-e5576334f648.png)
I cann't find any process of spawn-fcgi .
Am i using a wrong way to set cgi run environment?

**Comment by p-l-** [comment]
I don't know how to use `spawn-fcgi`. You can either:
* look for help on the `spawn-fcgi` project
* use `nginx` + `fcgiwrap` service (have a look at the `ivre/web` docker for help)
* use `apache` + `mod_cgi` (have a look at the `ivre/web-apache` docker for help)
Feel free to re-open if needed.
