### ISSUE TITLE
hello,how to run some tasks with python api

### ISSUE THREAD

**Issue by coco413** [cea-sec/ivre#379]
how to run some tasks with python ivre api

**Comment by p-l-** [comment]
Can you be more specific?

**Comment by coco413** [comment]
Is really good, I think it is difficult to receive a reply; that is, I need to scan now is distributed, but how to use the agent, two sets of equipment to which a deployment agent, how to open the docker agent, the other as a master

**Comment by p-l-** [comment]
I'm really sorry, but I don't understand your problem. Please explain as clearly as possible what you have done, what is working, and what you want to do. If you have Docker-related questions, please ask the Docker project support.

**Comment by coco413** [comment]
Sorry, sir, no explanation clear, I want to achieve a PC scan of the network now, which is corresponding to your Agent in the project, but the https://hub.docker.com/r/ivre/agent/, I now have a good download, but do not know how to open and master combination

**Comment by coco413** [comment]
How do you deploy between agent and master?

**Comment by p-l-** [comment]
Communications between the agent and the master work via `rsync`, either through a shared directory or a network link (`ssh` for example). Please refer to [IVRE's documentation](https://github.com/cea-sec/ivre/blob/master/doc/AGENT.md) and if needed to the `rsync` manual page.
