### ISSUE TITLE
No Display

### ISSUE THREAD

**Issue by CobbyJ** [cea-sec/ivre#405]
I have installed IVRE via Docker and works and i can load the webpage, but when i search an ip or anything i just get a blank display with NaN -

![ivre](https://user-images.githubusercontent.com/7136263/29454815-8561254e-8406-11e7-92c2-0b2cff67003b.jpg)

**Comment by p-l-** [comment]
This is the normal interface when no scan result has been added. You have to initialize the database, run scans and integrate them to your database.

If you have already added scan results and they are not showing up, please re-open it.
