### ISSUE TITLE
Scan problem - NMAP error - nmap: unrecognized option '--script-timeout'

### ISSUE THREAD

**Issue by mariudelros** [cea-sec/ivre#412]
Hello,
after the first install, all seems works but when i proceed with a scan like:

```
sudo ivre runscans --routable --limit 1000
```
the result is

```
nmap: unrecognized option '--script-timeout'ADDING TARGET 1 : 133.30.107.153ERROR: NMAP PROCESS IS DEAD
```

OR

```
sudo ivre runscans --routable --limit 1000 --output=XMLFork
```

result
```
nmap: unrecognized option '--script-timeout'
Nmap 6.40 ( http://nmap.org )
Usage: nmap [Scan Type(s)] [Options] {target specification} .....
```

Any idea?

thank you very much!!!

### IVRE Version
```
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.6.dev48

Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4]

L#106~14.04.1-Ubuntu SMP Mon Jun 26 18:10:19 UTC 2017 x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 2.7.2
    Python module py2neo: missing
    Python module sqlalchemy: 1.0.12
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: [unknown version]
    Python module MySQLdb: missing
    Python module dbus: 1.2.0
    Python module matplotlib: missing
```

**Comment by p-l-** [comment]
You are using an old version of Nmap, which does not implement the `--script-timeout` (see nmap/nmap#234) option, introduced in Nmap 7.25BETA2 (released one year ago).

You have two options:
  * Upgrade Nmap (I would recommend this anyway, at least for Nmap's scripts).
  * Prevent IVRE from using this option, by adding a line `NMAP_SCAN_TEMPLATES['script_timeout'] = None` to your `/etc/ivre.conf`.

**Comment by mariudelros** [comment]
Problem solved upgrading nmap!

thanks a lot

**Comment by jimthedj65** [comment]
Hi P
I had this very issue resolved and got the below different errors
WROTE ALL TARGETS
RTTVAR has grown to over 2.3 seconds, decreasing to 2.0
RTTVAR has grown to over 2.3 seconds, decreasing to 2.0
import-im6.q16: unable to open X server `XXX.18.XXX.XX:0' @ error/import.c/ImportImageCommand/358.
NO MORE DATA TO PROCESS

**Comment by p-l-** [comment]
Hi @jimthedj65,

I think that's not an error. The x11-screenshot Nmap script was simply not able to take a screenshot.

BTW, please open new issues for new problems rather than commenting on a closed ones.

**Comment by jimthedj65** [comment]
Hi P 

Ok thanks.
