### ISSUE TITLE
Add new filters: newhosts and newports (request)

### ISSUE THREAD

**Issue by r00t0vi4** [cea-sec/ivre#414]
I'd like to have the ability to control network hosts and ports which were recently added.
To implement this functionality ivre have to compare the current scan and the previous ones.
To show the results new filters have to be added: "newhosts" and "newports".
For example:
I need to scan my network every hour. Old scan results are archived.
When I add a new filter called "newhosts", ivre begin to search all the IPs in the current result and in the archive.
If IP was not found, it will be added to result table.
When "newports" filter is added, current results (each) are compared with previous.
The resulting table displays an IP with ports that were recently opened (i.e. these ports were closed in previous scans).
New ports must be highlited.

**Comment by p-l-** [comment]
Since the "archive" mechanism is going to be dropped, I'm closing this one. We'll see if/how this can be addressed when the "archive" thing is gone.
