### ISSUE TITLE
Question: how to perform a scan in order to see dot in the map

### ISSUE THREAD

**Issue by mariudelros** [cea-sec/ivre#416]
Hello Dear,
could you please explain us how to perform a scan (nmap or masscan or ivrescan), in order to show on the map, the result of the scan? 
I have imported inside my ivre implementation, your masscan modbus scan, and i see the dot on the map of the hosts of your scans. But all the scans that i perform does not appear on the map.

Thank you!

IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.6.dev48

Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4]

14.04.1-Ubuntu 

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 2.7.2
    Python module py2neo: 3.1.2
    Python module sqlalchemy: 1.0.12
    Python module psycopg2: 2.7.3.1 (dt dec pq3 ext lo64)
    Python module krbV: missing
    Python module PIL: [unknown version]
    Python module MySQLdb: 1.2.3
    Python module dbus: 1.2.0
    Python module matplotlib: 1.3.1

**Comment by p-l-** [comment]
To have the "Map" tool working on the GUI, you have to:
- Have downloaded and inserted the GeoIP data (as explained in the installation guides).
- Have scanned IPs that have location information in the GeoIP data.

You can check both of those items by doing (assuming that you have a scan result for IP x.y.z.t:
```
$ ivre ipdata x.y.z.t
x.y.z.t
    [...]
    coordinates (aa.aaa, bb.bbb)
    [...]
``` 

If you don't have a `coordinates` line in the output, you need to check with a "known" IP address (for example 8.8.8.8):
- if the result for 8.8.8.8 does not show a `coordiantes` line, you need to (download and) import GeoIP database (see the documentation)
- if the result for 8.8.8.8 has a `coordiantes` line, you need to scan IP addresses that have location information in the GeoIP database.

I'm closing this issue, please don't hesitate to comment or re-open it if you need more information or have a related comment or question.
