### ISSUE TITLE
Country code

### ISSUE THREAD

**Issue by shurik09** [cea-sec/ivre#420]
Hello

I have some question. How can I scan country Kosovo? ivre has -c option for scanning countries but there's no official country code for Kosovo

**Comment by p-l-** [comment]
As far as I can tell, the current database from Maxmind seem to handle Kosovo as a Serbian region, so maybe you can try something like `--region RS 02` or `--region RS 00` and see what you get.

We have to support Maxmind's format version 2 (https://dev.maxmind.com/geoip/geoip2/geolite2/).
