### ISSUE TITLE
Import error in builtins module

### ISSUE THREAD

**Issue by naisanza** [cea-sec/ivre#421]
### IVRE Version

```
root@ivre-world0:~# ivre version
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 24, in <module>
    from ivre import utils, tools
  File "/usr/local/lib/python2.7/dist-packages/ivre/utils.py", line 50, in <module>
    from builtins import bytes, int, object, range, str
ImportError: No module named builtins
```
Using ivre version: https://github.com/cea-sec/ivre/commit/6597d2e37e926ae1a13d2708aaf299bcae86a9e5

### Summary

When installing ivre in a default LXC Ubuntu 16.04 image, after building and installing from setup.py, `ivre` isn't able to run

### Actual behavior

Results from Ansible Playbook:
```
TASK [Database init, data download & importation] **********************************************************************************
  File "/usr/local/bin/ivre", line 24, in <module>
    from ivre import utils, tools
  File "/usr/local/lib/python2.7/dist-packages/ivre/utils.py", line 50, in <module>
    from builtins import bytes, int, object, range, str
ImportError: No module named builtins
```

### How to reproduce

Run Ansible Playbook: https://github.com/TheShellLand/antsable/blob/master/playbooks/ivre_lxc.yml

### More

LXC Ubuntu 16.04, Proxmox 5.0-31

**Comment by p-l-** [comment]
The `future` package is required (see `setup.py` and `requirements*.txt` files).
