### ISSUE TITLE
Masscan import returns 0 results imported.

### ISSUE THREAD

**Issue by rjmolesa** [cea-sec/ivre#428]
### IVRE Version
```
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.6

Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118]

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.5.1
    Python module py2neo: missing
    Python module sqlalchemy: 1.1.11
    Python module psycopg2: 2.7.3 (dt dec mx pq3 ext)
    Python module krbV: missing
    Python module PIL: 4.3.0
    Python module MySQLdb: 1.3.10
    Python module dbus: 1.2.4
    Python module matplotlib: 2.0.0
```
### Summary

It seems as if masscan xml import is failing.

### Expected behavior

I expected to see 1853 results imported.

### Actual behavior

Importing a masscan file containing 1853 up results via ```ivre scan2db masscanfile.xml``` outputs ```0 results imported```

**Comment by p-l-** [comment]
Is it possible that this scan result has already been imported?

Can you activate IVRE's debug mode (`echo "DEBUG = True" | sudo tee -a /etc/ivre.conf`) and try again?

**Comment by rjmolesa** [comment]
It clearly states that the Scan is already present in the database. Weird. It said 0 results imported since the first try.

**Comment by p-l-** [comment]
Then you can check whether the scan exists in the database using `scancli`. Maybe the scan is imported but IVRE fails to actually parse the data and hence import no result? When imported, what output produces `scancli --count`?

**Comment by rjmolesa** [comment]
The results appear to be in the database. Thanks!
