### ISSUE TITLE
NMAP VNC Screenshot script syntax error

### ISSUE THREAD

**Issue by ZeeshanSultan** [cea-sec/ivre#429]
### IVRE Version

```
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.6.dev70

Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609]

Linux ip-172-31-26-80 4.4.0-1038-aws #47-Ubuntu SMP Thu Sep 28 20:05:35 UTC 2017 x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.5.1
    Python module py2neo: 3.1.2
    Python module sqlalchemy: 1.1.15
    Python module psycopg2: 2.7.3.2 (dt dec pq3 ext lo64)
    Python module krbV: missing
    Python module PIL: 4.3.0
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing


```

### Summary

Got an error in one of your Nmap script for VNC Screenshots

### Expected behavior

```
cp /usr/share/ivre/nmap_scripts/*.nse /usr/share/nmap/scripts/
nmap --script-updatedb
```

After running the above commands Nmap db should've updated

### Actual behavior

> NSE: failed to initialize the script engine:
> /usr/bin/../share/nmap/nse_main.lua:254: /usr/bin/../share/nmap/scripts//vnc-screenshot.nse:93: unexpected symbol near '>'

### How to reproduce

I have performed a clean install following every single step of your process. It's a standard issue.

**Comment by p-l-** [comment]
Hi,

Can you report Nmap's version (`nmap --version` full output)?

**Comment by ZeeshanSultan** [comment]
Sure, here's the full output of the command

```
Nmap version 7.01 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.2.4 openssl-1.0.2g libpcre-8.38 libpcap-1.7.4 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
```

**Comment by p-l-** [comment]
As stated both in IVRE's `INSTALL.md` documentation file and in the script itself, Nmap version 7.25BETA2 minimum is required for this script.
