### ISSUE TITLE
IVRE Scan data

### ISSUE THREAD

**Issue by ZeeshanSultan** [cea-sec/ivre#449]
IVRE Version
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.6.dev70

Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609]

Linux ip-172-31-26-80 4.4.0-1038-aws #47-Ubuntu SMP Thu Sep 28 20:05:35 UTC 2017 x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.5.1
    Python module py2neo: 3.1.2
    Python module sqlalchemy: 1.1.15
    Python module psycopg2: 2.7.3.2 (dt dec pq3 ext lo64)
    Python module krbV: missing
    Python module PIL: 4.3.0
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing

Summary
Started a scan and no data was updated anywhere 
![ivreissue](https://user-images.githubusercontent.com/8667667/34460500-15a95cc6-ee32-11e7-9594-fcf5988b9fd6.jpg)

Expected behavior
The scan should've started but nothing in the runningscans collection and no data updated in the interface as well

Actual behavior
The command completed without returning any results

How to reproduce
I have performed a clean install following every single step of your process. It's a standard issue.

**Comment by p-l-** [comment]
The `ivre runscans` command only runs scans. It produces XML files in `scans/[scan name]/up/ip1/ip2/ip3/ip4.xml`.

You have to insert the scan results in the database, for example by running for example `ivre scan2db -r ./scans/*/up`.
