### ISSUE TITLE
Error while running agent daemon

### ISSUE THREAD

**Issue by ZeeshanSultan** [cea-sec/ivre#450]
### IVRE Version

```
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.6.dev70

Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609]

Linux ip-172-31-26-80 4.4.0-1038-aws #47-Ubuntu SMP Thu Sep 28 20:05:35 UTC 2017 x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.5.1
    Python module py2neo: 3.1.2
    Python module sqlalchemy: 1.1.15
    Python module psycopg2: 2.7.3.2 (dt dec pq3 ext lo64)
    Python module krbV: missing
    Python module PIL: 4.3.0
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing


```

### Summary

Tried to start agent based scans
The agent is already up and running
![ivreagent](https://user-images.githubusercontent.com/8667667/34470227-ea2fdcdc-ef4e-11e7-9813-c3aac34d5e04.jpg)

### Expected behavior

```
ivre runscansagentdb --daemon
```

After running the above commands the agents should've started scanning

### Actual behavior

![ivrescanissue](https://user-images.githubusercontent.com/8667667/34470223-d9cd5d10-ef4e-11e7-8a45-a303abecc158.jpg)

### How to reproduce

I have performed a clean install following every single step of your process. It's a standard issue.

**Comment by p-l-** [comment]
As the error message states, `rsync` cannot find the `ssh` command. Install an ssh client and try again. Re-open if needed.
