### ISSUE TITLE
Agent SSH Key Storage

### ISSUE THREAD

**Issue by ZeeshanSultan** [cea-sec/ivre#452]
Where do i place SSH keys of my agents ? so that `ivre runscansagentdb --daemon` can connect to my agents for assigning tasks because right now

![ivreagentsshkey](https://user-images.githubusercontent.com/8667667/34890801-27bd0846-f7f5-11e7-83e1-d0fc37a6df7e.jpg)

**Comment by p-l-** [comment]
Given your configuration, probably in `/root/.ssh/`. But that's not a question related to IVRE... Please Google "ssh passwordless authentication", or read the SSH documentation.
