### ISSUE TITLE
Ipinfo without argument is not working with postgresql.

### ISSUE THREAD

**Issue by Nutigoodpipes** [cea-sec/ivre#465]
### IVRE Version

$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.6.dev118

Python 2.7.5 (default, Aug  4 2017, 00:39:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.5.1
    Python module py2neo: 3.1.2
    Python module sqlalchemy: 1.1.15
    Python module psycopg2: 2.7.3.2 (dt dec pq3 ext lo64)
    Python module krbV: missing
    Python module PIL: 4.3.0
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing

### Summary

Ipinfo without argument is not working with postgresql.

### Expected behavior

Ten most recent results sorted and displayed.

### Actual behavior

All results are displayed (not ten last ones) and they are not sorted by descending order.

### How to reproduce

$ ivre ipinfo

### PostgreSQL version

$ postgres --version
postgres (PostgreSQL) 9.6.2

**Comment by p-l-** [comment]
Fixed in #470.
