### ISSUE TITLE
Screenshot is blank when SSL cert is invalid

### ISSUE THREAD

**Issue by jakevis** [cea-sec/ivre#478]
### IVRE Version

root@ivreclient:/# ivre version
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.7.dev6

Python 2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516]

Linux ivreclient 4.9.75-linuxkit-aufs #1 SMP Tue Jan 9 10:58:17 UTC 2018 x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.4.0
    Python module py2neo: 3
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: 4.0.0
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing

### Summary

When conducting a scan - the screenshots are placed into the ivre-share directory. However, whenever a site is scanned, the port 80 screenshot is good, but the 443 screenshot is white. I am guessing this is happening because the cert on these sites are invalid (for the IP anyway).
### Expected behavior

Ignore the cert, and generate the screenshot.

First shot (443):

![screenshot-13 107 3 128-443](https://user-images.githubusercontent.com/10895705/36133836-b60e4012-1035-11e8-8150-353df0dcfcdd.jpg)

Second shot (80):

![screenshot-13 107 3 128-80](https://user-images.githubusercontent.com/10895705/36133837-b6250c98-1035-11e8-8af2-0f8c289d2711.jpg)

### How to reproduce

ivre runscans --routable --asnum 80XX --output XMLFork --processes 60;

**Comment by p-l-** [comment]
Thanks for this report. #479 should fix this. Can you check and report if that's OK for you?
