### ISSUE TITLE
docker build -t ivre/web web-apache error!

### ISSUE THREAD

**Issue by malwaremuseum** [cea-sec/ivre#483]
### IVRE Version
```
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.7.dev16

Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516]

Linux ivreclient 4.14.0-kali3-amd64 #1 SMP Debian 4.14.12-2kali2 (2018-01-11) x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.4.0
    Python module py2neo: 3
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: 4.0.0
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
```

### Summary

Short summary.
system@truztee:~# docker build -t ivre/web web-apache
unable to prepare context: path "web-apache" not found

### Expected behavior
I need to download the ivre web apache package.

### Actual behavior
unable to prepare context: path "web-apache" not found

### Referenced from
https://github.com/cea-sec/ivre/blob/master/doc/DOCKER.md

**Comment by p-l-** [comment]
You must be in `docker/` repository.

**Comment by p-l-** [comment]
We have added a dedicated public image (`ivre/web-apache`). You can now get it from Docker Hub (`docker pull ivre/web-apache`).

Also, the documentation has been updated to make it clear from when you should run the command.

Please reopen this issue if needed.
