### ISSUE TITLE
Blank screenshot of websites with ssl or tls 

### ISSUE THREAD

**Issue by fjavierc** [cea-sec/ivre#490]
### IVRE Version
```
pepe@ivre3:~# ivre version
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 6befdbd

Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2]

Linux ivre3 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.6.0
    Python module py2neo: 3.1.2
    Python module sqlalchemy: 1.2.4
    Python module psycopg2: 2.5.4 (dt dec mx pq3 ext)
    Python module krbV: missing
    Python module PIL: [unknown version]
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing

```
### PhantomJS Version

```
pepe@ivre3:~# phantomjs --version
2.1.1
```

### Summary

Hello;

The same thing happens to me as what is said in #478 

My system is Debian 8.10, x64; with Ivre sources downloaded from Github

I have tried other versions of phantomjs and I get the same results.

As I know that some of the websites I analyze are not supported with SSLv3 but they do support TLS,  I modified the http-screenshot.nse script to indicate other arguments to phantomjs such as "--ssl-protocol = any", "--ssl-protocol = tlsv1" or " --web-security=false" but always with the same result. With the option "--ignore-ssl-errors=true"  I get the same results  ( blank screenshot )

Is it an operating system problem? Architecture? What about the phantomjs version?

### Expected behavior

Take a screenshot  of wesite, with colors, etc.

### Actual behavior

Take a blank screenshot, as #478 

### How to reproduce
Take a screenshot of a website with ssl/tsl  ( https://www.google.es ). For simplicity, just scan port 443
```
rpepe@ivre3:/tmp# nmap -p 443 www.google.es --script=http-screenshot

Starting Nmap 7.60 ( https://nmap.org ) at 2018-03-01 20:11 CET
Nmap scan report for www.google.es (216.58.201.131)
Host is up (0.030s latency).
Other addresses for www.google.es (not scanned): 2a00:1450:4003:804::2003
rDNS record for 216.58.201.131: mad06s25-in-f3.1e100.net

PORT    STATE SERVICE
443/tcp open  https
|_http-screenshot: Saved to screenshot-216.58.201.131-www.google.es-443.jpg

Nmap done: 1 IP address (1 host up) scanned in 0.76 seconds
```
The screenshot, blank, only take 16K:
```
pepe@ivre3:/tmp# du -hs screenshot-216.58.201.131-www.google.es-443.jpg 
16K	screenshot-216.58.201.131-www.google.es-443.jpg
```

### More
I do not know if it is my platform or phantomsjs problem so, any help is appreciated. If you think it is appropriate, close or delete this issue.

Thanks!

**Comment by p-l-** [comment]
Hi,

Did you reinstall the `http-screenshot.nse` file **after** upgrading IVRE?

**Comment by fjavierc** [comment]
Hi Pierre,

I use the last http-screenshot.nse from Github.

I have continued to investigate and have found other similar cases in which phantomjs creates blank screenshots of websites with ssl or tls enabled (tcp/443)

I start thinking that the problem I have is with phantomjs. Although I have used several versions (1.9.7, 1.9.8, 2.1.1, 2.13, 2.5) and I still have the same problem. I've also done tests on Debian 9.3 x64 and Ubuntu 16-04-3-server_x64, with the same results.

I have to try in a 32-bit architecture and a deployment of Ivre with docker.

Pierre, do you take right screenshots of websites with ssl/tls such as www.google.com?. If so, what operating system do you use? x32 o x64?, what version of phantomjs ?

Thanks!

**Comment by fjavierc** [comment]
Hello;

I've been doing a little more testing. In my case, I want to take screenshots of websites that I know have port 443 or 8443 open and have ssl/tls enabled ( https )

If I scan the port 443/tcp  of www.google.com with nmap, the http-screenshot.nse  script ( last  version Ivre, github )  generates the following .js file:

```
var system = require('system');
var webpage = require('webpage');
function capture(url, fname) {
    var page = webpage.create();
    page.open(url, function() {
        page.viewportSize = {
            width: 1024,
            height: 768
        };
        page.evaluate(function(){
            document.body.bgColor = 'white';
        });
        page.render(fname, {format: 'jpeg', quality: '90'});
        phantom.exit();
    });
}
capture("http://www.google.com:443", "screenshot-216.58.211.228-www.google.com-443.jpg");
setTimeout(phantom.exit, 300 * 1000);
```

As you can see, the url in the capture parameter contains "http" instead of "https". If I indicate "https" and manually  launch phantomjs ( 2.1.1), the screenshot is generated correctly.
```
...
capture("httpS://www.google.com:443", "screenshot-216.58.211.228-www.google.com-443.jpg");
...
```

```
root@ivre4:/tmp# phantomjs --web-security=false --ignore-ssl-errors=true google.js 

root@ivre4:/tmp# du -hs screenshot-216.58.211.228-www.google.com-443.jpg 
56K	screenshot-216.58.211.228-www.google.com-443.jpg
```
![screenshot-216 58 211 228-www google com-443](https://user-images.githubusercontent.com/15417469/36921153-8fb3315c-1e63-11e8-8884-7ff9935b7c8f.jpg)

Now I have to see how to indicate in http-screenshot.nse how to correctly form the url in the captura parameter. That is, if I scan a port of a computer such as 443, 8443 and also have ssl or tls enabled, the url should start with "https" and not with "http". I do not know if I explained well.

I do not know much about nse scripting or .js so I appreciate any help :-)

**Comment by fjavierc** [comment]
Hello,

As I was testing manually, I forgot to pass the "-sV" parameter to nmap.

In Ivre, for certain websites, as I continued to take blank screenshots, I had to pass the parameter "--web-security = false" to phantomJS (file http-screenshot.nse)

Thanks for everything. I think you can close this ticket.

**Comment by p-l-** [comment]
@fjavierc thanks a lot. It is true that `-sV` is needed for HTTPS screenshots. Maybe we could have a kind of detection for port like 443...

**Comment by p-l-** [comment]
@fjavierc can you try the patch proposed in #491 and report if you it works for you?

**Comment by fjavierc** [comment]
Hi @p-l- ;

The patch work for me but only if I delete this code from the patch
```
local string = require "string"
```

With the full pathc I  get this error:
```
root@ivre3:/tmp# nmap -p 443 --script=http-screenshot www.google.es -d

Starting Nmap 7.60 ( https://nmap.org ) at 2018-03-04 18:33 CET
....
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 18:33
NSE: Starting http-screenshot against www.google.es (216.58.201.131:443).
NSE: http-screenshot against www.google.es (216.58.201.131:443) threw an error!
/usr/local/bin/../share/nmap/scripts/http-screenshot.nse:63: variable 'stdnse' is not declared
stack traceback:
	[C]: in function 'error'
	/usr/local/bin/../share/nmap/nselib/strict.lua:80: in metamethod '__index'
	/usr/local/bin/../share/nmap/scripts/http-screenshot.nse:63: in function </usr/local/bin/../share/nmap/scripts/http-screenshot.nse:62>
	(...tail calls...)

Completed NSE at 18:33, 0.00s elapsed
...
```

So, just by applying the following patch (thanks to you) it has worked for me:

```
-  local ssl = port.version.service_tunnel == "ssl"
+  local ssl = port.version.service_tunnel == "ssl" or (
+    port.version.sevice_name == nil and string.match("https", port.service)
+  )
```

Example:
```
root@ivre3:/tmp# nmap -p 443 --script=http-screenshot www.google.com 

Starting Nmap 7.60 ( https://nmap.org ) at 2018-03-04 18:37 CET
Nmap scan report for www.google.com (216.58.211.196)
Host is up (0.041s latency).
Other addresses for www.google.com (not scanned): 2a00:1450:4003:801::2004
rDNS record for 216.58.211.196: mad01s25-in-f4.1e100.net

PORT    STATE SERVICE
443/tcp open  https
|_http-screenshot: Saved to screenshot-216.58.211.196-www.google.com-443.jpg

Nmap done: 1 IP address (1 host up) scanned in 2.74 seconds
root@ivre3:/tmp# du -hs screenshot-216.58.211.196-www.google.com-443.jpg 
56K	screenshot-216.58.211.196-www.google.com-443.jpg

OK !!
```

**Comment by p-l-** [comment]
I could not reproduce your issue with the patch. Anyway, I have updated the patch, can you tell me if this one works? Thanks!

**Comment by fjavierc** [comment]
Hi @p-l- ;  

I repeated the tests again, with the new patch and it works correctly.

**Comment by p-l-** [comment]
Thanks again @fjavierc, that's merged into master.
