### ISSUE TITLE
Passing Options to nmap from ivre runscan

### ISSUE THREAD

**Issue by superhac** [cea-sec/ivre#494]
I see in the help that theres a NMAP_PRESCAN_OPTS option, but i cant get it to work.  I am trying to use the nmap -Pn option to avoid pinging hosts.   How can I pass my options to nmap from the ivre runscan command?

Thanks!

**Comment by p-l-** [comment]
Hi,

Nmap "prescan" is **not** Nmap's "host discovery" scan (`-P*` options), it's another, preliminary, Nmap scan to decide which targets you want to include in the scan.

If you want to control Nmap's option, you have to create a scan template or change an existing one (see `config.NMAP_SCAN_TEMPLATES`). More precisely, you need to set `"pings"` to `"n"`.

**Comment by superhac** [comment]
Perfect.  Thats exactly what I was looking for!  For anyone else trying to figure out the nmap scan options I've put my /etc/ivre.conf below:

```
NMAP_SCAN_TEMPLATES["noping"]= {
     "traceroute": "",
     "osdetect": "",
      pings": "n",
     "ports": "21,22",
     "extra_options": ['-T2', '-sC'],
}
```
All the options that available can be pruned from this [src file](https://github.com/cea-sec/ivre/blob/master/ivre/nmapopt.py).

**Comment by p-l-** [comment]
See the `scripts_*` parts of the Nmap scan templates in the configuration. Also, to ask a question, please open a new issue rather than commenting in an old and closed one. Thanks!
