### ISSUE TITLE
Error load file python in webUI

### ISSUE THREAD

**Issue by doxuanthanh95** [cea-sec/ivre#495]
I try to config webUI for IVRE from source with this tutorial file https://github.com/cea-sec/ivre/blob/master/doc/FAST-INSTALL-AND-FIRST-RUN.md, when i load WebUI, have problem with file python in /usr/lib/cgi-bin/, cannot run this file with error Forbidden. Help me, please! I use ubuntu 16.04 with apache2
![image](https://user-images.githubusercontent.com/20521986/37693329-7d280868-2cf1-11e8-84f7-87d0c5aa795d.png)

**Comment by p-l-** [comment]
Can you report your web server's error log?

**Comment by p-l-** [comment]
Cannot reproduce, no answer.
