### ISSUE TITLE
Logcial Operators on Filters in the Web Interface

### ISSUE THREAD

**Issue by superhac** [cea-sec/ivre#497]
Maybe I'm not seeing it but is there logical operations that can be applied on the filters in the web interface of IVRE?  It appears that when I populate multiple "filters" with port numbers its an "AND" operation by default.  But when I try to filter on multiple IP's nothing shows.  Is there a way to specify an "OR" operation.

Thanks!

**Comment by p-l-** [comment]
There is no such options unfortunately.

For some parameters (for example, service names), you can use a regular expression (e.g., `service:/httpd|telnet/`), but that's not the case for the IP address.

For the IP addresses, the network (`1.2.3.0/24`) or range (`range:1.2.3.12-1.2.3.17`) filters are the only options.

**Comment by p-l-** [comment]
If you really need to be able to filter some hosts, you can also add them to a specific category when inserting the scan results, and then filter using the category.
