### ISSUE TITLE
Purge DB / Reset DB

### ISSUE THREAD

**Issue by superhac** [cea-sec/ivre#503]
Is there a simple way to wipe the DB and start fresh?

**Comment by p-l-** [comment]
You have not one but several DB in IVRE. You can use the CLI (`scandli`, `ipinfo`, `ipdata`, `flowcli`) associated with the DB you want to purge with `--init`. For example, to purge the Scan / Nmap database, use: `ivre scancli --init`.

**Comment by superhac** [comment]
Thats the one i was looking!  Thanks.  Also can you explain the archiving options that are available with the scan2db command.   What is archiving?  If every time I import a scan into the DB I want all the old entries to be cleared what option would I select?

Thanks!

**Comment by p-l-** [comment]
If you want to clear the DB when inserting new scan results, your best option is to `ivre scancli --init` before inserting.
