### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by spasaintk** [cea-sec/ivre#505]
### IVRE Version

IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.10

Python 2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516]

Linux  4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.4.0
    Python module py2neo: 3.1.2
    Python module sqlalchemy: 1.2.6
    Python module psycopg2: 2.7.4 (dt dec pq3 ext lo64)
    Python module krbV: [unknown version]
    Python module PIL: 4.0.0
    Python module MySQLdb: 1.3.7
    Python module dbus: 1.2.4
    Python module matplotlib: 2.2.2
    Python module bottle: 0.12.13

```

### Summary

Following the installation instructions I run the following command;

ivre ipdata --init

### Expected behavior

Command to complete without errors

### Actual behavior

It throws the following error;

ivre ipdata --init
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 84, in <module>
    main()
  File "/usr/local/bin/ivre", line 56, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/__init__.py", line 59, in get_command
    return getattr(__import__("%s.%s" % (__name__, name)).tools, name).main
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/ipdata.py", line 48, in <module>
    import ivre.geoiputils
  File "/usr/local/lib/python2.7/dist-packages/ivre/geoiputils.py", line 263, in <module>
    os.path.join(config.GEOIP_PATH, 'GeoIPCountry.csv'),
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'


### How to reproduce

Clean install through PIP

### More

-

**Comment by spasaintk** [comment]
Never mind, found the issue.

The PIP installer doesn't create the directory [INSTALL PREFIX]/share/ivre/geoip/ causing the above error.

**Comment by p-l-** [comment]
Nice catch, thanks for reporting this, and thanks for finding the fix!

**Comment by demokratlinux** [comment]
I am just learning. Tell me in detail what you need to do. I did not understand. Please.

**Comment by demokratlinux** [comment]
I created a folder /usr/lib/python2.7/share/ivre/geoip/ 
does not work. What to do? Please.

**Comment by p-l-** [comment]
The folder should probably be `/usr/share/ivre/geoip`.

**Comment by demokratlinux** [comment]
Thank you. Very grateful.

**Comment by demokratlinux** [comment]
The problem continues
apt-get install dokuwiki python-pil
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dokuwiki

Where to search for dokuwiki. Or what to do.???
Please

**Comment by p-l-** [comment]
It seems that [Dokuwiki is no longer packaged in Debian stable](https://packages.debian.org/search?keywords=dokuwiki), so you need to find another way to install it. Either from another Debian version's packages (since it is packaged for testing and oldstable), or from the Dokuwiki project page. You can have a look at `docker/web/Dockerfile` for a way to install it anyway.

Anyway, for your next questions, please do **not** comment on closed issues for unrelated problems.

**Comment by demokratlinux** [comment]
The problem continues
apt-get install dokuwiki python-pil
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dokuwiki

Where to search for dokuwiki. Or what to do.???
Please

**Comment by demokratlinux** [comment]
ivre runscans --routable --limit 1 --output=XMLFork 
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 84, in <module>
    main()
  File "/usr/local/bin/ivre", line 56, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/runscans.py", line 417, in main
    targets = ivre.target.target_from_args(args)
  File "/usr/local/lib/python2.7/dist-packages/ivre/target.py", line 476, in target_from_args
    state=args.state)
  File "/usr/local/lib/python2.7/dist-packages/ivre/target.py", line 215, in __init__
    geoiputils.get_routable_ranges(),
  File "/usr/local/lib/python2.7/dist-packages/ivre/geoiputils.py", line 274, in <lambda>
    get_routable_ranges = lambda: get_ranges_by_data('BGP.csv', lambda _: True)
  File "/usr/local/lib/python2.7/dist-packages/ivre/geoiputils.py", line 243, in get_ranges_by_data
    for start, stop in _get_by_data(datafile, condition):
  File "/usr/local/lib/python2.7/dist-packages/ivre/geoiputils.py", line 234, in _get_by_data
    fdesc = open(os.path.join(config.GEOIP_PATH, datafile))
IOError: [Errno 2] No such file or directory: '/usr/local/share/ivre/geoip/BGP.csv'

where to get it?           BGP.csv
Help.
