### ISSUE TITLE
GeoIP map not populated

### ISSUE THREAD

**Issue by timukas** [cea-sec/ivre#521]
Hi,

Scanned (imported) IP addresses are not populating GeoIP Map with 'dots'.

### IVRE Version

```
# ivre
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.10

Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
[GCC 7.3.0]

Linux kali 4.15.0-kali3-amd64 #1 SMP Debian 4.15.17-1kali1 (2018-04-25) x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.6.1
    Python module py2neo: 3.1.2
    Python module sqlalchemy: 1.2.5
    Python module psycopg2: 2.7.4 (dt dec mx pq3 ext lo64)
    Python module krbV: [unknown version]
    Python module PIL: 4.3.0
    Python module MySQLdb: 1.3.10
    Python module dbus: 1.2.6
    Python module matplotlib: 2.1.1
    Python module bottle: 0.12.13

```

### Summary

"ivre ipdata 211.237.XX.XX"  shows coordinates for provided ip address.
Country name and country flag are correctly visible in main IVRE web-gui.
But GeoIP map is without any coordinate 'dots'.

### Expected behavior

IP coordinates should be on the map.

### Actual behavior

IP coordinates are not on the map.

### update

I've also checked database information with "ivre scancli --json" and i see that coordinates (and other GeoIP data) are present:

{"state_reason_ttl": 242, "addr": 35XXXXX544, "endtime": "2018-05-15 XX:XX:X1", "os": {"fingerprint": "SCAN(V=7.70%E=4%D=5/15%OT=%CT=%CU=%PV=N%DS=17%DC=T%G=N%TM=5AFB14CD%P=x86_64-pc-linux-gnu)\nSEQ(II=I)\nU1(R=N)\nIE(R=Y%DFI=N%TG=FF%CD=S)\n"}, "state_reason": "echo-
reply", "schema_version": 9, "source": "XXX", "state": "up", "hostnames": [], "starttime": "2018-05-15 XX:XX:XX", "extraports": {"filtered": {"reasons": {"no-responses": 994, "admin-prohibiteds": 6}, "total": 1000}}, "openports": {"count": 0}, "infos": {"city":
"Daejeon", "region_code": "19", "coordinates": [36.3214, 127.4197], "country_code": "KR", "country_name": "Korea, Republic of", "as_name": "CMB Daejeon Broadcasting Co,.Ltd", "as_num": 3XXX4}..........

**Comment by p-l-** [comment]
Hi,

Thanks for reporting this bug. It should be fixed by the patch provided in #522. I'll merge the patch as soon as the tests pass (if they do, of course).

You'll have to import the scan results again.

Merging the PR will automatically close this ticket, please reopen it if that does not fix your issue.

**Comment by timukas** [comment]
Hi,

GeoIP map now has "dots", but latitude and longitude are messed up.

For example, coordinates for this IP "ivre ipdata 52.17.XX.XX"
52.17.XX.XX
    as_name Amazon.com, Inc.
    as_num 16509
    city Dublin
    region_code 07
    coordinates (53.3331, -6.2489)
    postal_code D02
    country_code IE
    country_name Ireland
"

Put dot on map as -6.2489, 53.3331.

**Comment by p-l-** [comment]
My bad...

**Comment by p-l-** [comment]
@timukas can you confirm your issue is fixed with the current master?

**Comment by timukas** [comment]
Yes, 

Ivre version "0.9.10.dev45" fixed.

thanks,

**Comment by p-l-** [comment]
Glad that's fixed! Thanks for your help.
