### ISSUE TITLE
ivre web UI dont show the results

### ISSUE THREAD

**Issue by 3g0r111** [cea-sec/ivre#531]
HI everyone the web UI ivre dont show me the results i think this problem happand because when i instal l web UI one comand when i entered in terminal return me an error:$ cd /usr/local/share/ivre/web/cgi-bin
bash: cd: /usr/local/share/ivre/web/cgi-bin: no such file or directory

### IVRE Version

IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.10

Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0]

Linux kali 4.14.0-kali3-amd64 #1 SMP Debian 4.14.12-2kali1 (2018-01-08) x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.6.1
    Python module py2neo: missing
    Python module sqlalchemy: 1.1.11
    Python module psycopg2: 2.7.3 (dt dec mx pq3 ext lo64)
    Python module krbV: missing
    Python module PIL: 4.3.0
    Python module MySQLdb: 1.3.10
    Python module dbus: 1.2.4
    Python module matplotlib: 2.0.0
    Python module bottle: 0.12.13

**Comment by p-l-** [comment]
Where have you installed IVRE?

**Comment by 3g0r111** [comment]
1-st time im install ivre throgh pip installer and when i initialise ipdata ivre returns me an error i start read mans and find answer i reinstall ivre manualy through setup.sh error disappeared but web face not shown the results of scan. sorry for my bad eanglish.

**Comment by p-l-** [comment]
`setup.py` is why, I need to know where. Can you run: `python -c 'from ivre import config; print(config.guess_prefix("web"))'`

**Comment by 3g0r111** [comment]
python -c 'from ivre import config; print(config.guess_prefix("web"))'
/home/egor/.local/share/ivre/web

**Comment by p-l-** [comment]
You need to really install IVRE. I don't know how this happened, but you need to uninstall IVRE and re-install it **as root** (`python setup.py build && sudo python setup.py install`).

If you only want the Web interface, you can also just run `ivre httpd` from a shell.

**Comment by 3g0r111** [comment]
thnx
