### ISSUE TITLE
Listing all certs

### ISSUE THREAD

**Issue by Maximevilla** [cea-sec/ivre#552]
Please try to follow this template. Also, please format your issue
properly (particularly to report code or command line output). You may
want to read
[Github's basic writing and formatting syntax](https://help.github.com/articles/basic-writing-and-formatting-syntax/).

### IVRE Version

```
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.10.dev105

Python 2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516]

Linux 0ef52ce1dad3 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.4.0
    Python module py2neo: 3
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: 4.0.0
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.13
```

### Summary

I am trying to retrieve and filter all { "ports.2.scripts.0.ssl-cert.subject.commonName": { $exists: true } }. 

They seem to not always be at the same place. and I do not just want the Top ones. Is there a way I do not know to get that? 

Because I am trying:

```
use ivre
db.hosts.find( { "ports.2.scripts.0.ssl-cert.subject.commonName": { $exists: true } })
```

Ps : Sorry, I come from the Mysql world...

### Expected behavior

Have a way to retrieve and list all certs. As sometimes the cert is the AD Domain name

### Unicorn One

Have a search engine 

### Actual behavior

Just get the TOP ones. 

### More

If not, is it possible to name all results scripts from NSE name and not just a number ?

So a non mongo user could find his way.

**Thanks**

*Maxime Villalongue*

**Comment by p-l-** [comment]
Just use: `db.nmap.searchscript(name='ssl-cert', values={'subject.commonName': {'$exists': True}})` or, preferably `db.nmap.searchscript(name='ssl-cert', values={'subject.commonName': re.compile('')}` (not formally the same meaning, but the latter is more portable and should work with PostgreSQL backend).

**Comment by Maximevilla** [comment]
Let's check if if i'm right. I have to add it in utils.py with a new elif.
And then to useit i build a newdocker from my git and this would be my new
ivreclient.
Am I taking the right way ?

2018-07-15 16:36 GMT+02:00 Pierre Lalet <notifications@github.com>:

**Comment by p-l-** [comment]
I'm not sure to understand what you want to do, I though you wanted a filter usable from the Python API.

If you just want to use `ivre scancli` to list all certificates' subjects, you can just use `ivre scancli --distinct ports.scripts.ssl-cert.subject`. You can use `--top` instead of `--distinct` to have the most common values.

The values displayed are Python object representations. You can use a simple script to get valid JSON and use the [jq](https://github.com/stedolan/jq) utility to extract the `commonName` values, for example:
```
$ ivre scancli --distinct ports.scripts.ssl-cert.subject | python -c "import ast,json,sys
for l in sys.stdin: print(json.dumps(ast.literal_eval(l)))" | jq .commonName
```

If you just need a specific field value, you can also just use `ivre scancli --distinct ports.scripts.ssl-cert.subject.commonName`.

Let us know if that answers your

**Comment by Maximevilla** [comment]
Yes!

Thanks. I've got all ways to do it working. I didn't think about the python
API

nevertheless, the first idea was to have a button like the screenshots one,
to list them all. Or, a filter displaying all values, not just the TOP 15
ones and then go threw.


But many thanks. I've got what I needed.

2018-07-16 12:55 GMT+02:00 Pierre Lalet <notifications@github.com>:
