### ISSUE TITLE
IPv6 support in active scan

### ISSUE THREAD

**Issue by japroc** [cea-sec/ivre#563]
Hello!

Recently was commited some code to support ipv6 in int2ip/ip2int functions: https://github.com/cea-sec/ivre/commit/36df3b592ee1e3c9fc33feb3e76b316612145c05
But it is still impossible to actively scan ipv6 targets. Why didnt you add additional field that describe addr type [(for sql)](https://github.com/cea-sec/ivre/blob/master/ivre/db/sql/tables.py#L331)? Right now ivre fails with addresses ::0808:0808 and 8.8.8.8, because integer representation is the same.
```
>>> ip2int('::0808:0808')
(134744072, 'ipv6')
>>> ip2int('8.8.8.8')
(134744072, 'ipv4')
>>> int2ip(134744072)
'8.8.8.8'
```
Do you plan to support ipv6 active scans? Actually it's enough to [add ipv6 regex](https://github.com/cea-sec/ivre/blob/master/ivre/tools/runscans.py#L82) and fix [one more place](https://github.com/cea-sec/ivre/blob/master/ivre/xmlnmap.py#L1202) to actively scan ipv6 ranges.

**Comment by p-l-** [comment]
Actually, it is a bit more complicated to support IPv6 with the MongoDB backend (which is the only non-experimental backend for now): `OverflowError: MongoDB can only handle up to 8-byte ints`

**Comment by p-l-** [comment]
For now, for the MongoDB backend, I can see three options:
* Use several fields to store the address (MongoDB can only store 64-bits **signed** integers).
* Use a list of integers for the "addr" field.
* Use a 16 bytes binary field.

All of them have drawbacks.

Several integers means handling them in filters, and that's the same for the list (with added complexity in expressions).

A binary field is harder to handle for some operations. It becomes complex (I have no idea for now on how we could do that, to be clear) to use the aggregation framework to get the most common networks (see [ivre/db/mongo.py](https://github.com/cea-sec/ivre/blob/master/ivre/db/mongo.py#L1789)).

Anyway this is important we'll have to find a solution. Thanks for the report, don't hesitate if you have other comments.

**Comment by Yookkee** [comment]
Yeah, i see, it's not easy to handle this problem.

But what if add ipv6 only for postgresql firstly, and then add this functionality for mongodb. I personally prefer psql over mongo. And this task doesn't look complicated. 

I actually have some code snippets to scan ipv6 subnets and ranges, process nmap output with ipv6 targets, import to and export from psql db.

So my needs end with runscans, scan2db, scancli (use --json flag, didnt test on others) tools. I didn't cover all occurrences of ipv6 targets, but i can share it with you some way?

**Comment by p-l-** [comment]
If you need this feature, I recommend that you create a pull request to provide it. I'm OK to merge a good solution that works only with SQL.

**Comment by p-l-** [comment]
And... we have the same problem with Sqlite3 backend or the (future) Elasticsearch backend.

Another (fourth) option, for MongoDB, would be:
* Use the hex-encoded value of the 16 bytes binary blob, as a string field (which allows for more operations in the aggregation framework).
