### ISSUE TITLE
Enhancement: Add the possibility to negate script filter 

### ISSUE THREAD

**Issue by Golbark** [cea-sec/ivre#577]
Hello,

I have been using Ivre for a while and thought it would be interesting to have the ability to do `!script:id` and `!script:id:output`. Sometimes it is interesting to know why a particular script didn't run or identify the hosts for which the output is different. It would also allow to identify "blank" results when the host timeout didn't allow nmap to store any result so they don't have any of the host scripts.

I'm ready to implement it myself. Just wondering if adding a "not" clause in the `searchscan` (and adding it to the GUI/CLI) would do the trick or if things might get more complicated.

Thanks.

**Comment by p-l-** [comment]
Hi,

Thanks for your interest in Ivre!

You would need to update `.searchscript()` methods (for the Python API), then update the CLI and Web UI filters.

Let us know if you need help, happy hacking!
