### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by AleksiGraba** [cea-sec/ivre#597]
I cant install it on the Raspberry Pi using the Install Manual
https://github.com/cea-sec/ivre/blob/master/doc/FAST-INSTALL-AND-FIRST-RUN.md
I did all, I cant scan with the --routable otion, and if i import the results, it wont show in the IVRE Web UI, it just show, counting, also after reboot. The first test was witch 100 results.

Does esitst a tutorial for a Raspberry Pi?
If I run the Setup Script:

root@NekokamisamaNYANYA:/home/pi/ivre# python setup.py build && sudo python setup.py install
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'extras_require'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running build
running build_py
copying ivre/VERSION -> build/lib.linux-armv7l-2.7/ivre
running build_scripts
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'extras_require'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
copying ivre/VERSION -> build/lib.linux-armv7l-2.7/ivre
running build_scripts
running install_lib
copying build/lib.linux-armv7l-2.7/ivre/VERSION -> /usr/local/lib/python2.7/dist-packages/ivre
running install_scripts
changing mode of /usr/local/bin/ivre to 755
running install_data
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/ivre-0.9.11.dev99.egg-info
Writing /usr/local/lib/python2.7/dist-packages/ivre-0.9.11.dev99.egg-info

And if I run the routable option:
root@NekokamisamaNYANYA:/home/pi/ivre# ivre runscans --routable --limit 100
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 84, in <module>
    main()
  File "/usr/local/bin/ivre", line 56, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/runscans.py", line 417, in main
    targets = ivre.target.target_from_args(args)
  File "/usr/local/lib/python2.7/dist-packages/ivre/target.py", line 478, in target_from_args
    state=args.state)
  File "/usr/local/lib/python2.7/dist-packages/ivre/target.py", line 216, in __init__
    rand=rand, maxnbr=maxnbr, state=state
  File "/usr/local/lib/python2.7/dist-packages/ivre/target.py", line 58, in __init__
    self.targetscount = len(targets)
OverflowError: long int too large to convert to int
root@NekokamisamaNYANYA:/home/pi/ivre#

I hope someone can help me.

**Comment by p-l-** [comment]
Hi,

Thanks for your interest in IVRE.

That is a limitation related to Python 2 and `len()`: a `len()` value can only be of type `int`. Here, your integer is too large (more than `sys.maxint`) for that.

You can:
- Switch to Python 3 (recommended, if you can).
- Try to patch the file `ivre/target.py`: replace `self.targetscount = len(targets)` by `self.targetscount = targets.__len__()` (dirty, should work; install IVRE again after you have changed `ivre/target.py`).

I'm on [gitter](https://gitter.im/cea-sec/ivre) if you need.

**Comment by AleksiGraba** [comment]
Hi,
I switched to Python 3.5, and installed all new, it makes no difference if I install it with pip or not.
I also installed all possible modules.

Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.7.2
    Python module py2neo: 4.1.0
    Python module sqlalchemy: 1.2.13
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: missing
    Python module MySQLdb: missing
    Python module dbus: 1.2.4
    Python module matplotlib: missing
    Python module bottle: 0.12.13


Now:

root@raspberrypi:~/ivre# sudo ivre runscans --routable --limit 1000
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 84, in <module>
    main()
  File "/usr/local/bin/ivre", line 56, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python3.5/dist-packages/ivre/tools/runscans.py", line 417, in main
    targets = ivre.target.target_from_args(args)
  File "/usr/local/lib/python3.5/dist-packages/ivre/target.py", line 478, in target_from_args
    state=args.state)
  File "/usr/local/lib/python3.5/dist-packages/ivre/target.py", line 216, in __init__
    rand=rand, maxnbr=maxnbr, state=state
  File "/usr/local/lib/python3.5/dist-packages/ivre/target.py", line 58, in __init__
    self.targetscount = len(targets)
OverflowError: cannot fit 'int' into an index-sized integer

**Comment by AleksiGraba** [comment]
Okay, I give up, I cant compile Mogodb in version 2.6.

**Comment by p-l-** [comment]
You need MongoDB **at least** 2.6, but anything higher should work. I would really recommend the current stable version (4.0)

**Comment by AleksiGraba** [comment]
I know but, it failed to compile, And i cant do it by myself, I need a tutorial or manual to do something like that.

**Comment by p-l-** [comment]
I'm sorry but for this problem, you'll have to ask for help to the MongoDB project. We are not MongoDB experts, and we use packages from either the MongoDB project or our Linux distributions.
