### ISSUE TITLE
nextpage sometimes can't work 

### ISSUE THREAD

**Issue by 294ru84** [cea-sec/ivre#615]
Please try to follow this template. Also, please format your issue
properly (particularly to report code or command line output). You may
want to read
[Github's basic writing and formatting syntax](https://help.github.com/articles/basic-writing-and-formatting-syntax/).

### IVRE Version

IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.11.dev144

Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516]

Linux 617ec43ba214 4.18.0-kali2-amd64 #1 SMP Debian 4.18.10-2kali1 (2018-10-09) x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.4.0
    Python module py2neo: 3
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: 4.0.0
    Python module MySQLdb: missing
    Python module dbus: 1.2.4
    Python module matplotlib: missing
    Python module bottle: 0.12.13

### Summary

after i use "scan2db" ,and use web ui
the nextpage function  can't work out,if error like "IOError: [Errno 2] No such file or directory: u'screenshot-180.115.145.131-8000.jpg'" happen.
i think "loading the screenshot error" cause i can't go to next page.

### Expected behavior

is there any tool to fix the loading next page error for ivre?or how to fix the web error?
thank you very much

**Comment by p-l-** [comment]
Hi,

Thanks for reporting this issue.

Where do you get the error? I suppose it is from the output of `ivre scan2db`? If so, how is it related to the web interface?

**Comment by 294ru84** [comment]
yes, the error is from the output of ivre scan2db.
it related it to web interface,because i take snapshot and try many times , the nextpage out of work always come with error like "IOError: [Errno 2] No such file or directory: u'screenshot-......" 
maybe it can be fixed with the web code(bypass screenshot, if not exit)......

**Comment by p-l-** [comment]
OK from what I understand it is unrelated to the web interface. This only means that the screenshot files are not in the current directory, where `ivre scan2db` expects to find them. Could you report where the screenshot files are, in comparison with the current directory when you run `ivre scan2db`?

**Comment by 294ru84** [comment]
attach to ivreclient
cd ivre-share
ivre runscans --routable --limit 100 --country JP --output=XMLFork


then i use another windows 
attach to ivreclient
ivre scan2db -c JP-001 -s MyFirstTest -r  /ivre-share/scans/COUNTRY-JP/up/

**Comment by 294ru84** [comment]
thank for your help,by the way
the nextpage out of work also come with "Error in pixGenerateHalftoneMask:"(runing scan2db)

**Comment by p-l-** [comment]
Again, this has nothing to do with the web interface. You should `cd` to the same directory before running the import (in your case, `cd ivre-share; ivre scan2db -c JP-001 -s MyFirstTest -r ./scans/COUNTRY-JP/up/`)
