### ISSUE TITLE
web can't deal with some scan result.......

### ISSUE THREAD

**Issue by 294ru84** [cea-sec/ivre#617]
result like below...............
    "ports" : [  
        {
            "state_reason" : "admin-prohibited",
            "state_reason_ttl" : NumberLong(236),
            "protocol" : "tcp",
            "state_state" : "filtered",
            "state_reason_ip" : "101.95.120.157",
            "state_reason_ip_0" : NumberLong(-9223372036854775808),
            "state_reason_ip_1" : NumberLong(-9223090564472276835),
            "port" : NumberLong(1025)
        }
    ]

thank for help

**Comment by p-l-** [comment]
You'll have to be more specific with what you did to get that, and why it does not match your expectations.

**Comment by 294ru84** [comment]
the web can't show nextpage sometimes......, then i go to db look for what happen, and i find result like i paste make it happen.............

**Comment by p-l-** [comment]
I'm sorry, but I cannot understand. We need **precise** error messages and descriptions, not "the web can't show nextpage sometimes". What happens exactly in the browser? When? What are the error messages from the web server? With issues and messages like these ones, we cannot help you.

**Comment by 294ru84** [comment]
If you scan a target with result like I paste,the web cannot handle it.
If you search  the target on web  to see the scan result ,you will see nothing on the right side of web(no error message).
Or can you tell me where is the web error messages  you want me provide you.
Or you can just scan the same ip,and search the IP on the web, you will know what i say

**Comment by p-l-** [comment]
Can you provide the output of `ivre scancli --json [the IP address you have scanned]`?

**Comment by 294ru84** [comment]
{
    "_id" : ObjectId("5bfea6a0dfde0f6138049be8"),
    "state_reason" : "echo-reply",
    "state_reason_ttl" : NumberLong(43),
    "os" : {
        "portused" : {
            "state" : "closed",
            "port" : "udp_41059"
        },
        "fingerprint" : "SCAN(V=7.40%E=4%D=11/28%OT=%CT=1%CU=41059%PV=N%DS=15%DC=T%G=N%TM=5BFEA524%P=x86_64-unknown-linux-gnu)\nSEQ(CI=I)\nSEQ(CI=I%II=I)\nT5(R=Y%DF=Y%T=40%W=0%S=Z%A=S+%F=AR%O=%RD=0%Q=)\nT6(R=Y%DF=Y%T=40%W=0%S=A%A=Z%F=R%O=%RD=0%Q=)\nT7(R=N)\nU1(R=Y%DF=N%T=40%IPL=164%UN=0%RIPL=G%RID=G%RIPCK=G%RUCK=G%RUD=G)\nIE(R=Y%DFI=N%T=40%CD=S)\n"
    },
    "addr_0" : NumberLong(-9223372036854775808),
    "schema_version" : 11,
    "source" : [ 
        "CN"
    ],
    "state" : "up",
    "hostnames" : [],
    "addr_1" : NumberLong(-9223090563143168239),
    "starttime" : ISODate("2018-11-28T14:23:00.000Z"),
    "extraports" : {
        "closed" : {
            "reasons" : {
                "resets" : NumberLong(984)
            },
            "total" : NumberLong(984)
        }
    },
    "openports" : {
        "count" : 0
    },
    "infos" : {
        "city" : "Shanghai",
        "region_code" : [ 
            "SH"
        ],
        "region_name" : [ 
            "Shanghai"
        ],
        "loc" : {
            "type" : "Point",
            "coordinates" : [ 
                121.3997, 
                31.0456
            ]
        },
        "continent_code" : "AS",
        "coordinates_accuracy_radius" : 200,
        "country_name" : "China",
        "registered_country_code" : "CN",
        "registered_country_name" : "China",
        "country_code" : "CN",
        "continent_name" : "Asia",
        "as_name" : "China Telecom (Group)",
        "as_num" : 4812
    },
    "endtime" : ISODate("2018-11-28T14:24:36.000Z"),
    "traces" : [ 
        {
            "hops" : [ 
                {
                    "rtt" : 0.13,
                    "ipaddr_1" : NumberLong(-9223090563286237183),
                    "ipaddr_0" : NumberLong(-9223372036854775808),
                    "ttl" : NumberLong(1)
                }, 
                {
                    "rtt" : 0.3,
                    "ipaddr_1" : NumberLong(-9223090562940796415),
                    "ipaddr_0" : NumberLong(-9223372036854775808),
                    "ttl" : NumberLong(2)
                }, 
                {
                    "rtt" : 78.08,
                    "ipaddr_1" : NumberLong(-9223090564488822783),
                    "ipaddr_0" : NumberLong(-9223372036854775808),
                    "ttl" : NumberLong(3)
                }, 
                {
                    "rtt" : 160.91,
                    "ipaddr_1" : NumberLong(-9223090565988614143),
                    "ipaddr_0" : NumberLong(-9223372036854775808),
                    "ttl" : NumberLong(4)
                }, 
                {
                    "rtt" : 161.36,
                    "host" : "border2.xe-0-3-1.avast-19.sef.pnap.net",
                    "ttl" : NumberLong(6),
                    "domains" : [ 
                        "border2.xe-0-3-1.avast-19.sef.pnap.net", 
                        "xe-0-3-1.avast-19.sef.pnap.net", 
                        "avast-19.sef.pnap.net", 
                        "sef.pnap.net", 
                        "pnap.net", 
                        "net"
                    ],
                    "ipaddr_1" : NumberLong(-9223090565099576675),
                    "ipaddr_0" : NumberLong(-9223372036854775808)
                }, 
                {
                    "rtt" : 162.99,
                    "host" : "core1.t6-1-bbnet1.sea.pnap.net",
                    "ttl" : NumberLong(7),
                    "domains" : [ 
                        "core1.t6-1-bbnet1.sea.pnap.net", 
                        "t6-1-bbnet1.sea.pnap.net", 
                        "sea.pnap.net", 
                        "pnap.net", 
                        "net"
                    ],
                    "ipaddr_1" : NumberLong(-9223090565099577328),
                    "ipaddr_0" : NumberLong(-9223372036854775808)
                }, 
                {
                    "rtt" : 163.93,
                    "host" : "be-130-pe01.seattle.wa.ibone.comcast.net",
                    "ttl" : NumberLong(8),
                    "domains" : [ 
                        "be-130-pe01.seattle.wa.ibone.comcast.net", 
                        "seattle.wa.ibone.comcast.net", 
                        "wa.ibone.comcast.net", 
                        "ibone.comcast.net", 
                        "comcast.net", 
                        "net"
                    ],
                    "ipaddr_1" : NumberLong(-9223090564556715943),
                    "ipaddr_0" : NumberLong(-9223372036854775808)
                }, 
                {
                    "rtt" : 196.91,
                    "ipaddr_1" : NumberLong(-9223090565052045230),
                    "ipaddr_0" : NumberLong(-9223372036854775808),
                    "ttl" : NumberLong(9)
                }, 
                {
                    "rtt" : 334.91,
                    "ipaddr_1" : NumberLong(-9223090562777663206),
                    "ipaddr_0" : NumberLong(-9223372036854775808),
                    "ttl" : NumberLong(12)
                }, 
                {
                    "rtt" : 322.73,
                    "ipaddr_1" : NumberLong(-9223090563143168239),
                    "ipaddr_0" : NumberLong(-9223372036854775808),
                    "ttl" : NumberLong(15)
                }
            ],
            "protocol" : "tcp",
            "port" : NumberLong(25)
        }
    ],
    "ports" : [ 
        {
            "state_state" : "filtered",
            "state_reason_ttl" : NumberLong(0),
            "protocol" : "tcp",
            "port" : NumberLong(19),
            "state_reason" : "no-response"
        }, 
        {
            "state_state" : "filtered",
            "state_reason_ttl" : NumberLong(0),
            "protocol" : "tcp",
            "port" : NumberLong(42),
            "state_reason" : "no-response"
        }, 
        {
            "state_state" : "filtered",
            "state_reason_ttl" : NumberLong(0),
            "protocol" : "tcp",
            "port" : NumberLong(80),
            "state_reason" : "no-response"
        }, 
        {
            "state_state" : "filtered",
            "state_reason_ttl" : NumberLong(0),
            "protocol" : "tcp",
            "port" : NumberLong(135),
            "state_reason" : "no-response"
        }, 
        {
            "state_state" : "filtered",
            "state_reason_ttl" : NumberLong(0),
            "protocol" : "tcp",
            "port" : NumberLong(139),
            "state_reason" : "no-response"
        }, 
        {
            "state_state" : "filtered",
            "state_reason_ttl" : NumberLong(0),
            "protocol" : "tcp",
            "port" : NumberLong(443),
            "state_reason" : "no-response"
        }, 
        {
            "state_state" : "filtered",
            "state_reason_ttl" : NumberLong(0),
            "protocol" : "tcp",
            "port" : NumberLong(445),
            "state_reason" : "no-response"
        }, 
        {
            "state_state" : "filtered",
            "state_reason_ttl" : NumberLong(0),
            "protocol" : "tcp",
            "port" : NumberLong(465),
            "state_reason" : "no-response"
        }, 
        {
            "state_state" : "filtered",
            "state_reason_ttl" : NumberLong(0),
            "protocol" : "tcp",
            "port" : NumberLong(587),
            "state_reason" : "no-response"
        }, 
        {
            "state_state" : "filtered",
            "state_reason_ttl" : NumberLong(0),
            "protocol" : "tcp",
            "port" : NumberLong(593),
            "state_reason" : "no-response"
        }, 
        {
            "state_reason" : "admin-prohibited",
            "state_reason_ttl" : NumberLong(236),
            "protocol" : "tcp",
            "state_state" : "filtered",
            "state_reason_ip" : "101.95.120.157",
            "state_reason_ip_0" : NumberLong(-9223372036854775808),
            "state_reason_ip_1" : NumberLong(-9223090564472276835),
            "port" : NumberLong(1025)
        }, 
        {
            "state_state" : "filtered",
            "state_reason_ttl" : NumberLong(0),
            "protocol" : "tcp",
            "port" : NumberLong(1068),
            "state_reason" : "no-response"
        }, 
        {
            "state_state" : "filtered",
            "state_reason_ttl" : NumberLong(0),
            "protocol" : "tcp",
            "port" : NumberLong(1434),
            "state_reason" : "no-response"
        }, 
        {
            "state_state" : "filtered",
            "state_reason_ttl" : NumberLong(0),
            "protocol" : "tcp",
            "port" : NumberLong(3128),
            "state_reason" : "no-response"
        }, 
        {
            "state_state" : "filtered",
            "state_reason_ttl" : NumberLong(0),
            "protocol" : "tcp",
            "port" : NumberLong(4444),
            "state_reason" : "no-response"
        }, 
        {
            "state_state" : "filtered",
            "state_reason_ttl" : NumberLong(0),
            "protocol" : "tcp",
            "port" : NumberLong(8080),
            "state_reason" : "no-response"
        }, 
        {
            "port" : -1,
            "scripts" : [ 
                {
                    "output" : "\nHOP  HOST        PROTOCOL  BLOCKED PORTS\n3    100.99.0.1  tcp       465,587\n",
                    "id" : "firewalk"
                }, 
                {
                    "output" : "PMTU == 1450",
                    "id" : "path-mtu"
                }
            ]
        }
    ],
    "categories" : [ 
        "SH"
    ]
}

**Comment by p-l-** [comment]
Is that the output from the MongoDB shell or from `ivre scancli --json`? Can you also report the output of `ivre version` (as requested by the template BTW)?

**Comment by 294ru84** [comment]
this is from MongoDB document

IVRE Version
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET pierre.lalet@cea.fr
Version 0.9.11.dev144

Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516]

Linux 617ec43ba214 4.18.0-kali2-amd64 #1 SMP Debian 4.18.10-2kali1 (2018-10-09) x86_64

Dependencies:
Python module Crypto: 2.6.1
Python module pymongo: 3.4.0
Python module py2neo: 3
Python module sqlalchemy: missing
Python module psycopg2: missing
Python module krbV: missing
Python module PIL: 4.0.0
Python module MySQLdb: missing
Python module dbus: 1.2.4
Python module matplotlib: missing
Python module bottle: 0.12.13

**Comment by p-l-** [comment]
> this is from MongoDB document

OK. This is what I asked you:

> Can you provide the output of `ivre scancli --json [the IP address you have scanned]`?

I'm sorry but if you don't provide the information I need, I cannot help you.

**Comment by 294ru84** [comment]
I can only see the DB content(can't get ip from web).so when i try to use ivre scancli --json [the IP address you have scanned], I don't know what is "ipaddr_1" : NumberLong(-9223090563143168239) meaning...then that is why I can't give you json result,can you just add the data to db, or tell me how to convert -9223090563143168239 to IP, then I can give you the json result

**Comment by 294ru84** [comment]
I del the result from db ,and web can show result normally again. Can you just try to add the result directly to the db , and search the ip ,then you can repeat the error, not just ask me provide you the funking Json data, I have tell you how to repeat the error,but you didn't even try it…

**Comment by 294ru84** [comment]
You can't solve the web bug ,not meaning the bug solved…ok? Or the bug is the web normal function?

**Comment by 294ru84** [comment]
If I can give you json data I will give you at first time, and what is your problem to add the data directly to the db? Before the bug fix,you close it is not how open-source works ok?

**Comment by p-l-** [comment]
Again, I do not have to work for you for free. I cannot see a reason why I would help you, considering how you ask.

FYI, I have blocked your account from "contributing" to @cea-sec repositories since this conversation is going nowhere, and I have lost enough time with you; I hope you will understand (but I do not care if you do not).

Next time you need (free) help and support from open-source developers, may be you could try to be polite and respectful, and to provide the information they ask and need (not the information you think they need, since you do not know what they need, do you?).

Keep in mind they owe you nothing: they have no obligation to fix your issues.

Have a good day.
