### ISSUE TITLE
wrong WSGI path at install

### ISSUE THREAD

**Issue by gelim** [cea-sec/ivre#647]
Hi,

on a clean Ubuntu 18.04 install if you follow documentation `doc/FAST-INSTALL-AND-FIRST-RUN.md`  you'll have an apache2 issue `Target WSGI script not found or unable to stat: /usr/share/ivre`  pinpointed to the following line `# echo 'Alias /cgi "/usr/share/ivre/web/wsgi/app.wsgi"' > conf-enabled/ivre.conf`.

The install via `sudo python setup.py install` instead is done in `/usr/local/share/ivre` , so the WSGI path should be updated to:
```
echo 'Alias /cgi "/usr/local/share/ivre/web/wsgi/app.wsgi"' > conf-enabled/ivre.conf`
```

(or change the setup.py install to `sudo python setup.py install --prefix=/usr`)

By the way, for copy-paste ergonomics, would be great to drop for each terminal line first char "#" or "$". Loosing this info does not seems to be dramatic as all the commands after `sudo -s` are run by root anyway.

Cheers,

-- 
Mathieu

**Comment by p-l-** [comment]
Hi @gelim! Thanks for that, should be fixed soon. About the `$` or `#`, initially they were here to prevent people from copy/pasting the lines without checking they were matching their environment...
