### ISSUE TITLE
not authorized on ivre to execute command { drop: "scans" }

### ISSUE THREAD

**Issue by gusleig** [cea-sec/ivre#701]
Please try to follow this template. Also, please format your issue
properly (particularly to report code or command line output). You may
want to read
[Github's basic writing and formatting syntax](https://help.github.com/articles/basic-writing-and-formatting-syntax/).

### IVRE Version

IVRE - Network recon framework
Copyright 2011 - 2019 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.12.dev130

Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]

Linux kali 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.8.0
    Python module py2neo: missing
    Python module sqlalchemy: 1.3.1
    Python module psycopg2: 2.7.7 (dt dec pq3 ext lo64)
    Python module krbV: missing
    Python module PIL: 5.4.1
    Python module MySQLdb: 1.3.10
    Python module dbus: 1.2.8
    Python module matplotlib: 3.0.2
    Python module bottle: missing

### Summary
Trying to install the database objects. Gives an error

### Expected behavior

I would expect it to create the objects

### Actual behavior

sudo ivre scancli --init
This will remove any scan result in your database. Process ? [y/N] y
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 84, in <module>
    main()
  File "/usr/local/bin/ivre", line 56, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python3.7/dist-packages/ivre/tools/scancli.py", line 122, in main
    db.db.nmap.init()
  File "/usr/local/lib/python3.7/dist-packages/ivre/db/mongo.py", line 3418, in init
    self.db[self.columns[self.column_scans]].drop()
  File "/usr/local/lib/python3.7/dist-packages/pymongo/collection.py", line 1099, in drop
    dbo.drop_collection(self.__name, session=session)
  File "/usr/local/lib/python3.7/dist-packages/pymongo/database.py", line 826, in drop_collection
    session=session)
  File "/usr/local/lib/python3.7/dist-packages/pymongo/database.py", line 555, in _command
    client=self.__client)
  File "/usr/local/lib/python3.7/dist-packages/pymongo/pool.py", line 584, in command
    user_fields=user_fields)
  File "/usr/local/lib/python3.7/dist-packages/pymongo/network.py", line 158, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib/python3.7/dist-packages/pymongo/helpers.py", line 155, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: not authorized on ivre to execute command { drop: "scans" }

### How to reproduce

I don't know how to reproduce. It started after I installed the mongodb as a daemon on kali linux.

I can log into the database without problems

Any help is welcome.
Thanks

**Comment by p-l-** [comment]
Hi,

It looks like a "normal" permission denied error (in MongoDB) to me. What user are you using in IVRE's configuration?

If you can, please provide /etc/ivre.conf (and ~/.ivre.conf if relevant).

**Comment by gusleig** [comment]
I'm using the root user

root@kali:~/Documentos/ivre# whoami
root

**Comment by gusleig** [comment]
how does IVRE access mongodb, I mean, with which user?

**Comment by p-l-** [comment]
I was referring to the MongoDB user, not the system user. It is given in the configuration. If no configuration is provided, IVRE tries to connect without authenticating to the database. Did you set a MongoDB authentication?

**Comment by gusleig** [comment]
AH ok, MongoDB is using an  user I created called mongodb 
I put this user into the sudo group 

**usermod -aG sudo mongodb**

```
root@kali:~/Documentos/ivre# systemctl status mongodb
● mongodb.service - An object/document-oriented database
   Loaded: loaded (/lib/systemd/system/mongodb.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2019-06-14 11:08:07 -03; 6s ago
     Docs: man:mongod(1)
 Main PID: 5960 (mongod)
    Tasks: 14 (limit: 1131)
   Memory: 100.3M
   CGroup: /system.slice/mongodb.service
           └─5960 /usr/bin/mongod --quiet --config /etc/mongodb.conf

jun 14 11:08:07 kali systemd[1]: Started An object/document-oriented database.
```


but the problem persisted

**Comment by gusleig** [comment]
Well, found the problem, I disabled security on /etc/mongodb.conf

```
security:
    authorization: disabled

```
I'm wondering, how to run IVRE with mongodb security authorization?

thanks for your help

**Comment by p-l-** [comment]
Create a config file `/etc/ivre.conf` and add a line that reads:
```
DB = "mongodb://username:password@127.0.0.1:27017/ivre"
```

**Comment by p-l-** [comment]
Please reopen if needed.
