### ISSUE TITLE
Question on nfdump file format and command to run it

### ISSUE THREAD

**Issue by charanyajayaraaman** [cea-sec/ivre#704]
### IVRE Version

root@ivreclient:/# ivre version                                       
IVRE - Network recon framework
Copyright 2011 - 2019 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.12.dev2

Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516]

Linux ivreclient 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.4.0
    Python module py2neo: 3
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: 4.0.0
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.13

### Summary

Successfully set-up ivre docker container and additionally installed neo4j into a sidecar container accessible on the same docker-network (neo4j:7474). I was able to copy nmap.xml files into ivre-share folder and lookup results in localhost:80
Additionally, I am also trying to include NetFlow data to the data stream. I have 3 file outputs from nfdump: .json, .csv & nfcapd. 
I have a 2 part question here:
1. Which is the correct file format to use for nfdump that flow2db and ne04j can read? Is it .json, .csv or nfcapd?
2. Which command do I use to successfully copy the nfdump file into ivre-client and project results onto my localhost 80:80 browser?

### Expected behavior
$ ivre flow2db ivre-share/nfcapd.201904090015.nfdump 
When the above command is run, I expect the nfcapd file to be copied to the ivre-share folder and hence see these results in localhost:80
### Actual behavior

But when the command is run, I get the following error message:
root@ivreclient:/# ivre flow2db ivre-share/nfcapd.201904090015.nfdump 
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 84, in <module>
    main()
  File "/usr/local/bin/ivre", line 56, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/flow2db.py", line 103, in main
    with fileparser(fname, args.pcap_filter) as fdesc:
  File "/usr/local/lib/python2.7/dist-packages/ivre/parser/netflow.py", line 78, in __init__
    super(NetFlow, self).__init__(cmd, cmdkargs)
  File "/usr/local/lib/python2.7/dist-packages/ivre/parser/__init__.py", line 40, in __init__
    self.proc = subprocess.Popen(cmd, **cmdkargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

### How to reproduce

If needed, include the exact commands others can try to reproduce your
issue.

### More

Attached screenshots:
1. docker ps results
![docker ps results](https://user-images.githubusercontent.com/16803615/59775663-8e745000-927f-11e9-9744-0bc26c855d64.png)
2. localhost:7474 --- neo4j browser
![image](https://user-images.githubusercontent.com/16803615/59776078-32f69200-9280-11e9-9841-f0ddfbf51fd9.png)

**Comment by p-l-** [comment]
PR #706 will add `nfsdump` binary to the `ivre/client` image.

**Comment by charanyajayaraaman** [comment]
Hello Pierre, 
Thank you very much for responding to our query very quickly. 
As per your suggestion, i was able to install nfdump in my ivre-client container. 

**Expected Behavior:**
When I run the command $ ivre flow2db ivre-share/nfcapd.201904090015.nfdump I want the nfcapd file copied into flow2db

**Actual Behavior:**
root@ivreclient:/# ivre flow2db ivre-share/nfcapd.201904090015.nfdump 
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 84, in <module>
    main()
  File "/usr/local/bin/ivre", line 56, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/flow2db.py", line 104, in main
    for rec in fdesc:
TypeError: iter() returned non-iterator of type 'NetFlow'
root@ivreclient:/# ivre flow2db ivre-share/nfcapd.201904090015        
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 84, in <module>
    main()
  File "/usr/local/bin/ivre", line 56, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/flow2db.py", line 104, in main
    for rec in fdesc:
TypeError: iter() returned non-iterator of type 'NetFlow'

**Note**
Please let me know if you would prefer that I opened a new issue for this comment. Appreciate your time and help!

**Comment by p-l-** [comment]
This is a bug in IVRE (it must be the last one :-) ).

This patch should fix it, you can apply it the file `/usr/local/lib/python2.7/dist-packages/ivre/tools/flow2db.py` in your container and it should work:
```patch
 diff --git a/ivre/parser/__init__.py b/ivre/parser/__init__.py
index 3604744..eeff404 100644
--- a/ivre/parser/__init__.py
+++ b/ivre/parser/__init__.py
@@ -22,6 +22,9 @@
 import subprocess
 
 
+from builtins import object
+
+
 from ivre.utils import FileOpener
 
 
```

**Comment by p-l-** [comment]
I have updated the Docker image, so you can just `docker pull ivre/client` again, you should have an image with `nfdump` installed and this bug fixed.

Thanks a lot for reporting it!
