### ISSUE TITLE
NMAP_SCAN_TEMPLATE structure

### ISSUE THREAD

**Issue by 0xCC00FFEE** [cea-sec/ivre#819]
Hello, 
First of all, thank you for such great project!
Secondly, I wanted to ask about how NMAP_SCAN_TEMPLATES structure gets converted into a valid nmap command. 
For example, what would be the corresponding template of the following command:
`nmap -v -sS -A -T5 -p 20,22,53,1000-1010 target`

I'm aware of `--output CommandLine` switch usage which shows the corresponding command for a given NMAP_SCAN_TEMPLATES structure, however there are couple of questions, for example what if I wanted to append switch `-T5` to my command, how would I do that in the structure to append `-T5` at scan time to the nmap command? I tried adding values `-T5` and `T5` to `extra_options` field, however both failed to form a valid nmap command with `-T5` switch. Some other structure keys are more intuitive, like the `-v` switch which is based on the `verbosity` value in the structure, however the rest are (to me at least) totally ambiguous.

Did you think of using a very simple structure of `nmap_key = nmap_value`? So in order to form the above nmap command, the newly suggested structure would have the values:
```
NMAP_SCAN_STRUCT = {}
NMAP_SCAN_STRUCT["ports"] = "20,22,53,1000-1010"
NMAP_SCAN_STRUCT["scan_options"] = "-v -sS -A -T5"
```

**Comment by p-l-** [comment]
Hi,

Since `-T*` options are not specifically handled by `ivre.nmapopt`, you need to use `extra_options` and set it to `["-T5"]`.

Adding the following line to IVRE's configuration file should work:
```Python
NMAP_SCAN_TEMPLATES["default"]["extra_options"] = ["-T5"]
```

It could be a good idea to handle `-T*` options specifically (if that is something users often want to change).

**Comment by 0xCC00FFEE** [comment]
This is great, thank you!
