### ISSUE TITLE
Web API - subnet requests not handled

### ISSUE THREAD

**Issue by Frky** [cea-sec/ivre#859]
### IVRE Version

```
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2019 Pierre LALET <pierre.lalet@cea.fr>
Version 5d57fe0d

Python 2.7.16 (default, Apr 6 2019, 01:42:57) 
[GCC 8.3.0]

```

### Summary

Requests for subnet (e.g., 10.0.0.0/8) are not handled by the Web API - return code is 404.

### Expected behavior

The expected behaviour would be a HTTP 200 OK, with a json containing info equivalent to the the result of the corresponding request
performed using the CLI (*i.e.*, `ivre ipinfo 10.0.0.0/8`).

### Actual behavior

The server returns a HTTP 404 Not Found HTML page.

### How to reproduce

```
curl --referer "http://XX.XX.XX.XX/" http://XX.XX.XX.XX/cgi/passivedns/10.0.0.0/8
```

**Comment by p-l-** [comment]
Fixed in #896
