### ISSUE TITLE
"ivre scan2db" returns 0 when importing a non-existing file

### ISSUE THREAD

**Issue by duncrow** [cea-sec/ivre#921]
### IVRE Version
IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.14.dev250

Python 2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0]

Linux IVRE 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.7.1
    Python module py2neo: missing
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: missing
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.15
    Python module OpenSSL: missing
    Python module tinydb: missing

### Summary
When the import file cannot be imported, "ivre scan2db" terminates with return code 0. This makes it difficult to detect this condition whilst running the import unattended or via script.

### Expected behavior
On error, a non-zero return code should be returned.

### How to reproduce
root@somehost:~# ivre scan2db does-not-exist
WARNING:ivre:Exception (file 'does-not-exist')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/scan2db.py", line 104, in main
    masscan_probes=args.masscan_probes, callback=callback,
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 1637, in store_scan
    scanid = utils.hash_file(fname, hashtype="sha256")
  File "/usr/local/lib/python2.7/dist-packages/ivre/utils.py", line 780, in hash_file
    with open_file(fname) as fdesc:
  File "/usr/local/lib/python2.7/dist-packages/ivre/utils.py", line 768, in open_file
    return FileOpener(fname)
  File "/usr/local/lib/python2.7/dist-packages/ivre/utils.py", line 713, in __init__
    with open(fname, 'rb') as fdesc:
IOError: [Errno 2] No such file or directory: 'does-not-exist'
INFO:ivre:0 results imported.

root@somehost~# echo $?
0

### More
Thank you for your great work!

**Comment by p-l-** [comment]
Hi,

Thanks for this issue.

What do you think would be best: return non-zero as soon as at least one file could not be inserted? or when no file could be inserted? Also, an already imported file won't be imported either.

Do you think we should return a non-zero status when the user attempts to insert an already inserted scan?

**Comment by duncrow** [comment]
Personally, I would prefer a non-zero return value, if at least one file could not be imported. 
Inserting an already inserted scan is fine for me, since the import itself is working. Although it might influence the data-quality, it's not an import error per se.

**Comment by p-l-** [comment]
Works for me!
