### ISSUE TITLE
Recuperation de geoip impossible

### ISSUE THREAD

**Issue by lefrancais** [cea-sec/ivre#923]
Bonjour il est impossible de télécharger les tar.gz de geoip country ect....
Et quand je veux les télécharger manuellement le site ne fonctionne pas et apparemment jai lu sur ce site qu'il avait changer leur caractéristiques de téléchargement comment remédier à ce problème ? Merci

**Comment by p-l-** [comment]
Duplicature #922. Voir mon commentaire sur cette issue.
