### ISSUE TITLE
scan2db INFO:ivre:0 results imported.

### ISSUE THREAD

**Issue by lefrancais** [cea-sec/ivre#926]
IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.15

Python 2.7.17 (default, Apr 15 2020, 17:20:14) 
[GCC 7.5.0]

Linux thor-OptiPlex-3050 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64

Dependencies:
    Python module pymongo: 3.10.1
    Python module py2neo: 4.3.0
    Python module sqlalchemy: 1.3.16
    Python module psycopg2: 2.8.5 (dt dec pq3 ext lo64)
    Python module cryptography: 2.9.2
    Python module krbV: [unknown version]
    Python module PIL: 6.2.2
    Python module MySQLdb: 1.2.5
    Python module dbus: 1.2.6
    Python module matplotlib: 2.2.5
    Python module bottle: 0.12.18
    Python module OpenSSL: 19.1.0
    Python module tinydb: 3.15.2

usage: ivre [COMMAND]

available commands:
  airodump2db
  arp2db
  auditdom
  db2view
  flow2db
  flowcli
  getmoduli
  httpd
  ipcalc
  ipdata
  iphost
  ipinfo
  macinfo
  p0f2db
  passiverecon2db
  passivereconworker
  plotdb
  runscans
  runscansagent
  runscansagentdb
  scan2db
  scancli
  scanstatus
  version
  view
  zeek2db

Try ivre help [COMMAND]

$ ivre scan2db -c ROUTABLE,ROUTABLE-CAMPAIGN-001 -s MySource -r \ scans/ROUTABLE/up
INFO:ivre:0 results imported.

Why doesn't anything matter? I don't see what's wrong. Everything's okay.

**Comment by p-l-** [comment]
Could you ask your questions in English? That would help other people facing similar issues...

1. Do you have any files at all in `scans/ROUTABLE/up`? If so, can you provide the output of `find scans/ROUTABLE/up -type f`?

1. Have your scan results already been imported? IVRE uses files hashes to prevent a file result from being imported twice.

**Comment by lefrancais** [comment]
Good evening. Thank you for helping me.
here are the results of the order:

$ scans/ROUTABLE/up -type f
bash: scans/ROUTABLE/up: is a folder

and I haven't imported anything yet.

**Comment by p-l-** [comment]
Thanks for your answer. You have forgotten the `find`

**Comment by lefrancais** [comment]
sorry 

find ??
find scans/ROUTABLE/up -type f   ??

**Comment by p-l-** [comment]
I **think** you might have included a backslash `\` that was originally protecting the newline character that now makes IVRE try to open ` scans/ROUTABLE/up` (note the initial space) instead of `scans/ROUTABLE/up`.

If I'm right, this should work: `ivre scan2db -c ROUTABLE,ROUTABLE-CAMPAIGN-001 -s MySource -r scans/ROUTABLE/up`.

Anyway, this issue made me realize that `ivre scan2db` used with `-r` does **not** raise an error when the directory does not exist (while without `-r` you get a Python exception), which is clearly something I need to fix.

**Comment by lefrancais** [comment]
Just perfect. Thank you so much for your help.
I'll close the issue.
