### ISSUE TITLE
Exploring for "product" finds "unknown", clicking on "unkown" yields no results.

### ISSUE THREAD

**Issue by duncrow** [cea-sec/ivre#931]
### Version

IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.14.dev250

Python 2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0]

Linux IVRE 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.7.1
    Python module py2neo: missing
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: missing
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.15
    Python module OpenSSL: missing
    Python module tinydb: missing

### Summary

Exploring for "product" brings up a nice list of products, some of them labeled as "unknown". Clicking on "unknown" yields no results.

### Expected behavior

Clicking on "unknown" should bring up a list of the ip-adresses where the product couldn't be determined.

### Actual behavior

No results displayed.

### How to reproduce

Difficult to reproduce without my dataset, therefore pls see the (anonymized) screenshots. I get the data from importing the result of automatic nmap scans with the following parameters against my network:

"-n -sT -T4 -F --open --max-parallelism 4 -oX output.xml"
and
"-n -sT -T4 -p 443,8443 -sV --script ssl-enum-ciphers --open -oX ciphers.xml"

<img width="1342" alt="explore" src="https://user-images.githubusercontent.com/25221563/80965815-854a8e00-8e13-11ea-9d6b-4b2b6c22995e.png">
<img width="906" alt="null-null" src="https://user-images.githubusercontent.com/25221563/80965828-8b406f00-8e13-11ea-9727-0045f8f00d57.png">
<img width="901" alt="https-null" src="https://user-images.githubusercontent.com/25221563/80965840-91365000-8e13-11ea-8eea-ec2ca0f7f64b.PNG">

**Comment by p-l-** [comment]
Thanks for reporting this. It is obviously a bug, and it exists in the current development version (shame on me, I have been aware of this long ago, but never took the time to fix it).
