### ISSUE TITLE
Question: Best way to update an existing installation

### ISSUE THREAD

**Issue by duncrow** [cea-sec/ivre#951]
### IVRE Version

IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.14.dev250

Python 2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0]

Linux IVRE 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.7.1
    Python module py2neo: missing
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: missing
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.15
    Python module OpenSSL: missing
    Python module tinydb: missing

### Summary

I installed IVRE as per https://doc.ivre.rocks/en/latest/install/fast-install-and-first-run.html#install some time ago. Now I'd like to update my installation, so what's the best way to do this? Update sources with "git pull" and just run "python setup.py build && sudo python setup.py install" again? I couldn't find anything in your otherways really excellent documentation, hope I wasn't just to blind to see :)

**Comment by p-l-** [comment]
Thanks for your kind words. You did not miss it, this information does not exist in the documentation (while it should).

I guess running `git pull` then `python setup.py build && python setup.py install` again should do.

However, this will not remove files that have been removed. I guess the easiest way would be to remove (as you can) the existing files and then use `pip` to install (and then update) IVRE.

**Comment by duncrow** [comment]
Just gave it a try, worked like a charm. ("ivre view --update-schema" was needed afterwards, no problems there either.) Thank you for your quick response!
