### ISSUE TITLE
Feature Request - Please add SMB Signing Information to the options for Win Hosts

### ISSUE THREAD

**Issue by aryanguenthner** [cea-sec/ivre#959]
Please try to follow this template. Also, please format your issue
properly (particularly to report code or command line output). You may
want to read
[Github's basic writing and formatting syntax](https://help.github.com/articles/basic-writing-and-formatting-syntax/).

### IVRE Version
IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.15.dev57

Python 2.7.18 (default, Apr 20 2020, 20:30:41) 
[GCC 9.3.0]

Linux kali 5.6.0-kali2-amd64 #1 SMP Debian 5.6.14-1kali1 (2020-05-25) x86_64

### Summary
Please add SMB Signing Information to the options for Win Hosts.

Short summary.
Currently when you click Win on the top menu there are only:

XP/445
SMB Shares
>Writeable
MS-SQL empty password

Please add:
SMB Signing

Ref:
https://nmap.org/nsedoc/scripts/smb-security-mode.html
https://nmap.org/nsedoc/scripts/smb2-security-mode.html

**Comment by p-l-** [comment]
Hi,

You can use: `script:<script_name>` and `script:<script_name>:<value>` where `<value>` may be a regular expression. In your case, you may want to use `script:smb-security-mode:"/message_signing: disabled/"`.

Please let us know if that does not work for you.

Pierre
