### ISSUE TITLE
Tensorflow 

### ISSUE THREAD

**Issue by UnknowST** [cea-sec/ivre#960]
///BUG

`from PIL import Image
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Conv2D, BatchNormalization, Activation, MaxPool2D, Dropout, Flatten, Dense
from tensorflow.keras import Model
from tensorflow import keras
type = ['湿垃圾', '干垃圾', '可回收垃圾', '有害垃圾']
model_save_path = './checkpoint/VGG16.ckpt'
model = tf.keras.models.Sequential()
latest=tf.train.latest_checkpoint(model_save_path)
model.load_weights(latest)

image_path = input("输入图片路径:")
img = Image.open(image_path)
image = plt.imread(image_path)
plt.set_cmap('gray')
plt.imshow(image)
img = img.resize((28, 28), Image.ANTIALIAS)
img_arr = np.array(img.convert('L'))
img_arr = 255 - img_arr

img_arr = img_arr / 255.0

# img_arr= img_arr.reshape(img_arr.shape[0], 28, 28, 1)
x_predict = img_arr[tf.newaxis, ...]
x_predict=x_predict.reshape(x_predict.shape[0],28,28,1)
result = model.predict(x_predict)

pred = tf.argmax(result, axis=1)
print('\n')
print(type[int(pred)])

plt.pause(10)     #图片停住10秒
plt.close()`

`Traceback (most recent call last):
  File "D:/pycharm/AI/Test2/rubapp.py", line 16, in <module>
    model.load_weights(latest)
  File "D:\anacond\envs\TF2.1\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 234, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "D:\anacond\envs\TF2.1\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1183, in load_weights
    if _is_hdf5_filepath(filepath):
  File "D:\anacond\envs\TF2.1\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1500, in _is_hdf5_filepath
    return (filepath.endswith('.h5') or filepath.endswith('.keras') or
AttributeError: 'NoneType' object has no attribute 'endswith'`

**Comment by p-l-** [comment]
Please:
  - follow the issue template;
  - read the contributing guidelines;
  - format your issue properly;
  - explain the issue.
