### ISSUE TITLE
API

### ISSUE THREAD

**Issue by lprat** [cea-sec/ivre#961]
### IVRE Version
From docker
```
IVRE - Network recon framework
Copyright 2011 - 2019 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.14.dev127

Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
[GCC 8.3.0]

Linux b59a3cd8b3a5 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.7.1
    Python module py2neo: missing
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: missing
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.15
    Python module OpenSSL: missing
    Python module tinydb: missing

```

### Summary

Use API for update entries nmap.db and add enrichment values.

### Expected behavior

I would like add news information from XML nmap format.
I thought it was possible by use:
curl -i -XPOST -F 'source=add_info' -F 'result=@/home/lionel/test.xml' 'https://ivre/cgi/scans'
When address IP (X.X.X.X) exist in db, this call not work (return: {"count": 0}) -> no update to add {scan} in list [] for this IP (ref: curl -i -k -XGET -H "referer: https://ivre/" 'https://ivre/cgi/scans?q=X.X.X.X'). 

This action of adding a scan for an existing IP address in db.nmap database is only possible with the command: ivre scan2db file.xml?

Thank.
Lionel

**Comment by p-l-** [comment]
A result (XML file here) can only be imported once. I think this explains your result.

**Comment by p-l-** [comment]
I'm closing this issue. Please comment here if it is not fixed.
