### ISSUE TITLE
Can we update dockerfile to use nmap 7.8.0

### ISSUE THREAD

**Issue by nibiwodong** [cea-sec/ivre#968]
ivre still use nmap 7.7.0. However there are many bugs at 7.7.0
The dockerfile is :
`https://github.com/cea-sec/ivre/blob/master/docker/client/Dockerfile`

I think use nmap 7.8.0 is better.

**Comment by p-l-** [comment]
Thanks for this issue.

The images have been updated on Docker Hub so you can now either build your own images based on the `docker/*` subfolder from this repository or pull `ivre/*` images from Docker Hub.
