### ISSUE TITLE
Migration to new docker images/new MongoDB

### ISSUE THREAD

**Issue by xme** [cea-sec/ivre#978]
I have a *very* old IVRE instance in a docker. (more than 2y old).
I need to find back some old scan details. I deployed a new set of IVRE docker images (latest) and used mongodump/mongorestore to migrate the data. But when I try to browse hosts from the web frontend, no hosts are found.
I presume that a migration of the data is not sufficient. Any step that I missed?

**Comment by p-l-** [comment]
If it is **very** old, it is possible that the `view` purpose did not even exist at that time (see https://doc.ivre.rocks/en/latest/overview/principles.html#purposes). What I think you should do, from a client:
```sh
# first, migrate the scan data
ivre scancli --update-schema
# then, create the view
ivre view --count
# if the previous command returns "0", you can run:
ivre view --init
ivre view2db nmap
```

Hope this helps!

**Comment by xme** [comment]
Tx! Tested your solution but it wasn't successful :(
I think I'll start over with a fresh DB...

**Comment by p-l-** [comment]
That's probably a better solution, because you might also have a MongoDB database that the new MongoDB server cannot read (I had not though of that possible issue in my first answer). Can we close this issue?

**Comment by p-l-** [comment]
Please reopen if needed.
