### ISSUE TITLE
ERROR: Invalid Referer header. Check your configuration.

### ISSUE THREAD

**Issue by OsamaMahmood** [cea-sec/ivre#981]
### IVRE Version

Insert here the output of the command `ivre version`, displayed as
code. For example:

```
$ ivre version
IVRE - Network recon frameworkCopyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.15.dev101
Python 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
Linux 4fceaf793752 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64
Dependencies:
    Python module pymongo: 3.7.1    
    Python module sqlalchemy: missing
    Python module psycopg2: missing    
    Python module cryptography: missing
    Python module krbV: missing    
    Python module PIL: 5.4.1
    Python module MySQLdb: missing    
    Python module dbus: missing
    Python module matplotlib: missing    
    Python module bottle: 0.12.15
    Python module OpenSSL: missing    
    Python module tinydb: missing

```
### Summary

We are running IVRE using Docker and we are trying to set up HTTP Auth on the IVRE web client and for doing so we have configured a reverse proxy using Nginx the config is like this:

```
server {
  listen 8080 default_server;
  location / {
    proxy_pass http://localhost:8081;

    auth_basic_user_file /etc/nginx/.htpasswd;
    auth_basic "Access restricted";


  }
}
```

Now, this config works and prompts us for the credentials for HTTP auth after logging in we are unable to see any results on the dashboard. And we get the following error:

<img width="1871" alt="image" src="https://user-images.githubusercontent.com/12585224/92449110-fdb2c880-f1d2-11ea-9557-15354f9f8f2f.png">

But if we access the dashboard without reverse proxy we are getting the results on the dashboard.

<img width="1909" alt="image" src="https://user-images.githubusercontent.com/12585224/92449447-8598d280-f1d3-11ea-8ae0-5173bc7e5bce.png">

### How to reproduce

Run IVRE using docker on a different port than 80 and the using Nginx to reverse proxy to the IVRE web UI.

**Comment by p-l-** [comment]
Hi,

You need to configure IVRE to tell the Web server which referrer URLs should be accepted. That is explained in the documentation: https://doc.ivre.rocks/en/latest/install/config.html#anti-csrf

**Comment by OsamaMahmood** [comment]
In which file do I have to add that?

**Comment by p-l-** [comment]
You simply need to edit the file `/etc/ivre.conf` on the Web server.

**Comment by OsamaMahmood** [comment]
Thanks, we figured it out 👍
