### ISSUE TITLE
Cannot merge host documents. Schema versions differ

### ISSUE THREAD

**Issue by ubushan** [cea-sec/ivre#982]
**IVRE Version**
Version 0.9.15

**Output:**

```
$ ivre db2view nmap
Traceback (most recent call last):
  File "/home/shell/.local/bin/ivre", line 88, in <module>
    main()
  File "/home/shell/.local/bin/ivre", line 60, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/home/shell/.local/lib/python2.7/site-packages/ivre/tools/db2view.py", line 135, in main
    for elt in itr:
  File "/home/shell/.local/lib/python2.7/site-packages/ivre/view.py", line 440, in to_view
    next_recs.append(next(itrs[i]))
  File "/home/shell/.local/lib/python2.7/site-packages/ivre/view.py", line 404, in from_nmap
    cur_rec = db.view.merge_host_docs(cur_rec, rec)
  File "/home/shell/.local/lib/python2.7/site-packages/ivre/db/mongo.py", line 1680, in merge_host_docs
    rec = super(MongoDBActive, self).merge_host_docs(rec1, rec2)
  File "/home/shell/.local/lib/python2.7/site-packages/ivre/db/__init__.py", line 2119, in merge_host_docs
    rec2.get("schema_version")))
ValueError: Cannot merge host documents. Schema versions differ (16 != 18)
```

How to fix this problem :( ?
Thanks

**Comment by p-l-** [comment]
You need to update the documents from the `scan` feature first. Run `ivre scancli --update-schema`, then run `ivre db2view nmap`.

**Comment by ubushan** [comment]
> You need to update the documents from the `scan` feature first. Run `ivre scancli --update-schema`, then run `ivre db2view nmap`.
Thanks for your answer.
I had already updated schema but it not fixed this problem.

`$ ivre scancli --update-schema
INFO:ivre:Migrating column 0 from version None to 1
INFO:ivre:Creating new indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version None to 1 DONE
INFO:ivre:Migrating column 0 from version 1 to 2
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 1 to 2 DONE
INFO:ivre:Migrating column 0 from version 2 to 3
INFO:ivre:Creating new indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 2 to 3 DONE
INFO:ivre:Migrating column 0 from version 3 to 4
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 3 to 4 DONE
INFO:ivre:Migrating column 0 from version 4 to 5
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 4 to 5 DONE
INFO:ivre:Migrating column 0 from version 5 to 6
INFO:ivre:Creating new indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 5 to 6 DONE
INFO:ivre:Migrating column 0 from version 6 to 7
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 6 to 7 DONE
INFO:ivre:Migrating column 0 from version 7 to 8
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 7 to 8 DONE
INFO:ivre:Migrating column 0 from version 8 to 9
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 8 to 9 DONE
INFO:ivre:Migrating column 0 from version 9 to 10
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 9 to 10 DONE
INFO:ivre:Migrating column 0 from version 10 to 11
INFO:ivre:Creating new indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 10 to 11 DONE
INFO:ivre:Migrating column 0 from version 11 to 12
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 11 to 12 DONE
INFO:ivre:Migrating column 0 from version 12 to 13
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 12 to 13 DONE
INFO:ivre:Migrating column 0 from version 13 to 14
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 13 to 14 DONE
INFO:ivre:Migrating column 0 from version 14 to 15
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 14 to 15 DONE
INFO:ivre:Migrating column 0 from version 15 to 16
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 15 to 16 DONE

$ ivre db2view nmap
Traceback (most recent call last):
  File "/home/shell/.local/bin/ivre", line 88, in <module>
    main()
  File "/home/shell/.local/bin/ivre", line 60, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/home/shell/.local/lib/python2.7/site-packages/ivre/tools/db2view.py", line 135, in main
    for elt in itr:
  File "/home/shell/.local/lib/python2.7/site-packages/ivre/view.py", line 440, in to_view
    next_recs.append(next(itrs[i]))
  File "/home/shell/.local/lib/python2.7/site-packages/ivre/view.py", line 404, in from_nmap
    cur_rec = db.view.merge_host_docs(cur_rec, rec)
  File "/home/shell/.local/lib/python2.7/site-packages/ivre/db/mongo.py", line 1680, in merge_host_docs
    rec = super(MongoDBActive, self).merge_host_docs(rec1, rec2)
  File "/home/shell/.local/lib/python2.7/site-packages/ivre/db/__init__.py", line 2119, in merge_host_docs
    rec2.get("schema_version")))
ValueError: Cannot merge host documents. Schema versions differ (16 != 18)`

**Comment by p-l-** [comment]
You need to update the schema with the latest version of IVRE: the problem is that you have inserted results with a version that works with the schema version 18, and you are now using an older version, that only works with the schema version 16.

**Comment by p-l-** [comment]
Please reopen if needed.

**Comment by ubushan** [comment]
Thanks, but this commands not solve this problem :(
```
ivre scancli --update-schema
ivre db2view nmap
```

**Comment by p-l-** [comment]
> You need to update the schema with the latest version of IVRE: the problem is that you have inserted results with a version that works with the schema version 18, and you are now using an older version, that only works with the schema version 16.

**Comment by ubushan** [comment]
Thanks, the command `ivre scancli --init` fixed my problem
